### ISSUE TITLE
Fatal Error after Adding Image Widget

### ISSUE THREAD

**Issue by redmetyellowcreative** [netrivet/prophoto-issues#103]
I got a fatal error after unsuccessfully trying to add an image widget. It seemed that the dialogue box had kind of timed out, so I clicked it about 3 or 4 seperate times to see if it would fix itself. After refreshing, I got this error:

Fatal error: Call to a member function addColumn() on a non-object in /home/redmetyellow/public_html/wp-content/themes/prophoto6/vendor/netrivet/prophoto-classes/src/Infrastructure/WordPress/Design/Mapper/TemplateMapper.php on line 141

Site is at http://www.redmetyellowcreative.com/

**Comment by brianium** [comment]
@redmetyellowcreative dang! are you able to access admin at all? if so would you mind opening this issue through the help widget? I may need to get some FTP info from you, and a public issue on GitHub might not be the safest place to get that :)

**Comment by redmetyellowcreative** [comment]
Yes, I can still access admin! I'll get on there now!

**Comment by brianium** [comment]
@redmetyellowcreative we have been chatting through zendesk, so I am going to close this out
