### ISSUE TITLE
Column alignment issues with right-aligned vertical menu

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#123]
Steps to reproduce:

1. Create a row with 4 equal-span columns
2. Put a text widget in each of the left two columns
3. Put a search widget in the 3rd from left column
4. Put a menu widget in the last column, type=vertical alignment=right

View site at tablet breakpoint -- widgets align super funky.  See below screenshots:

![screen shot 2016-01-08 at 9 38 57 pm](https://cloud.githubusercontent.com/assets/7050938/12213924/c971b5da-b650-11e5-93e8-ed68695435b9.jpg)

![screen shot 2016-01-08 at 9 39 20 pm](https://cloud.githubusercontent.com/assets/7050938/12213926/cf0ece7e-b650-11e5-8661-7120d0a654bf.jpg)

**Comment by meatwad5675** [comment]
@jaredh159 I couldn't replicate this locally.  Could you show me?
