### ISSUE TITLE
Installing pulled my whole site down.

### ISSUE THREAD

**Issue by heatherburks** [netrivet/prophoto-issues#157]
I followed all instructions and activated the theme, now my whole site is down: http://meettheburks.com

It gives me this error and won't let me switch back themes or anything: This version of ProPhoto requires that PHP be compiled with the PDO mysql driver. Please activate a different theme, and contact your web-host to have them enable this required extension.

**Comment by heatherburks** [comment]
I contacted my host and they said that was already enabled. The theme worked fine on my "fake site" but I was told to try the Test Drive plugin and it pulled my whole real site down.

**Comment by heatherburks** [comment]
I deleted the theme through FTP but I don't understand why it won't activate on my main but did fine on the tester?

**Comment by jaredh159** [comment]
Heather, sorry about that, can you open a ticket by emailing us directly at support (at) prophoto6.zendesk.com so we can get login credentials and figure this out?
