### ISSUE TITLE
Grid overlays don't always perfectly match size

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#162]
Causing a bit of the photo to show through the bottom when the overlay is shown.  This only appears at certain screen resolutions.

![grid-overlay-bug](https://cloud.githubusercontent.com/assets/7050938/12399313/34ea6314-bde7-11e5-8f90-1bd8c33d49f4.png)

**Comment by jaredh159** [comment]
+1 Jennifer Clare

**Comment by lalunecreative** [comment]
+1
