### ISSUE TITLE
Add menu type for scrolling to block div

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#163]
Matt Hudson's description:

> Ability to link a menu item to a block. So let's say I wanted to have a single page website with all the content just on the single page. I could create links in the menu which, when clicked would go to the various sections. Sections being the blocks of content in the customizer I've set.
>
> Basically you would create a block, name it "bio" add all your widgets and content, and then add a menu item somewhere to link to it, so that when you click it on the front end it just automatically scrolls down to that content section.

**Comment by jaredh159** [comment]
+1 Melissa Love (she wants to be able to scroll to any anchor link)

**Comment by northfolkco** [comment]
+1 Northfolk

We are doing this now with anchor blocks but its really choppy. Maybe with a smooth scrolling speed as well.

**Comment by lalunecreative** [comment]
I almost wish these were sort of shortcoded. That way we could name a block or piece of content with a shortcode we set ourselves, then just paste it into anything we want somewhere else on the page (doesn't have to be a menu item, could  be a prophoto icon widget) and it just automatically go to it when linked. It's just an alternate way of thinking about it.
