### ISSUE TITLE
Installation gone wrong!

### ISSUE THREAD

**Issue by lapequesalsera** [netrivet/prophoto-issues#192]
I did everything right and i got to install (without activating) p6, once I started "trying" to work on the website, it kicked me out of WP... so, I signed in again and now I do not see the "prophoto" item on the menu, I see everything else there but prophoto, so.. I checked on the themes and I see prophoto 6, it is not activated and once I hit "live preview" it tells me I have no permission to see it...?

I was on the right track and I am not sure what is going on... Also, as I signed OUT of the WP, I tried looking at my website, and it's a mess... I am sure something is going on and you are on it already!

Rox

**Comment by jaredh159** [comment]
Rox,

Sorry about that! Can you open a ticket by emailing us directly at support (at) prophoto6.zendesk.com so we can figure this out? Send your FTP and WordPress login in that email (not in reply to this) so that we can start troubleshooting right away.
