### ISSUE TITLE
Expose font-style controls for widget content

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#200]
`<h1>`, `<h2>`, etc..
maybe `<ul>`, `<ol>`, `<blockquote>` ... other stuff?

This would be maybe a stop-gap until we implement https://github.com/netrivet/prophoto-issues/issues/199 or maybe they both complement each other.

**Comment by jaredh159** [comment]
+1 Jennifer Clare

**Comment by jaredh159** [comment]
+1 Jonathan Ryder

**Comment by jaredh159** [comment]
@meatwad5675 @brianium I'm getting the sense from both normal customers and designers that we probably need to fast-track this one and sneak it in as soon as possible.  It shouldn't be a lot of work either.

**Comment by brianium** [comment]
:+1:

**Comment by jaredh159** [comment]
+1 Bruce from BVD

**Comment by lalunecreative** [comment]
Can we also throw in that "remove formatting" option I talked about awhile back? Every time you paste anything in it carries over font style, background color and everything else. At the moment I'm pasting into an email, removing the format and then pasting it back into the text widget.

**Comment by northfolkco** [comment]
Hey @lalunecreative you can also paste that into the Tools > Source Code to get that as plain text and it will remove the formatting as well

**Comment by lalunecreative** [comment]
Oh nice, well that'll make things a little quicker at least!

**Comment by benjamintennant** [comment]
+1 David in #1754 - He wants an option to paste as plain text without going to the source code area.
