### ISSUE TITLE
Add tooltip to "All display types" icon in responsive settings selector

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#215]
![screen shot 2016-01-22 at 12 41 23 am](https://cloud.githubusercontent.com/assets/11544705/12513219/a01a0ab2-c0ea-11e5-9202-42fa839ebe2c.png)

https://prophoto6.zendesk.com/agent/tickets/603

**Comment by jaredh159** [comment]
done with first tooltips pass
