### ISSUE TITLE
Arrow key navigation for galleries

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#218]

**Comment by lalunecreative** [comment]
+ Finger movements as well for magic mouse. So awesome to add this.

**Comment by benjamintennant** [comment]
+1 Eddie Bojorquez ticket 808

**Comment by danjonlam** [comment]
+1 Michelle 3898

**Comment by benjamintennant** [comment]
+1 Jackson Eddy ticket 145769

**Comment by postmastersteve** [comment]
+1 Joshua Zuckerman ticket 148139

**Comment by benjamintennant** [comment]
+1 Marios Katsaros ticket 149013

**Comment by benjamintennant** [comment]
+1 Wale Akingbade ticket 151913

**Comment by danjonlam** [comment]
+1 Laurie Lomax ticket 154796

**Comment by danjonlam** [comment]
+1 Brian Friedman ticket 158604

**Comment by danjonlam** [comment]
+1 Candy Yu ticket 159993

**Comment by postmastersteve** [comment]
+1 Ellen Ross ticket 163370

**Comment by postmastersteve** [comment]
+1 Vitor Maciel ticket 166181

**Comment by danjonlam** [comment]
+1 Eline Stoffer ticket 168118

**Comment by benjamintennant** [comment]
+1 Adam Trujillo ticket 168245

**Comment by benjamintennant** [comment]
+1 Shauna Benoit ticket 168154

**Comment by benjamintennant** [comment]
+1 Nicole Ooms ticket 168961

**Comment by lalunecreative** [comment]
Something else needs to be added along these lines for Carousel galleries on desktop. Currently you can use the mouse to click and drag between images in a Carousel gallery, but the mouse should change to a finger that should close fingers on click when holding. Right now there's no indication that you can even browse the gallery that way because the pointer stays the same.

**Comment by benjamintennant** [comment]
+1 Gretchen Villaluna Baria ticket 169198

**Comment by postmastersteve** [comment]
Added in ProPhoto 6.21.0
https://github.com/netrivet/prophoto-issues/blob/master/CHANGELOG.md#6210
