### ISSUE TITLE
Custom Grid Items

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#220]
Restore what you can do in P4 and P5 -- the ability to create grids out of uploaded images linked to any URL.

**Comment by benjamintennant** [comment]
+1 Tanya #2105 - wants the ability to control content of excerpt/title text in grid items

**Comment by benjamintennant** [comment]
+1 Sven #2174 - wants ability to customize title and excerpt in grid items that custom grids would give

**Comment by benjamintennant** [comment]
+1 Fritz ticket 2303

**Comment by reneebell** [comment]
any update on this??? tutorial on grids says that custom links are available, but I cant find how to do it?
thanks

**Comment by jaredh159** [comment]
@reneebell the feature is done, and will be released in the next feature auto-update. That should be around mid-week this week, so just a few more days.

**Comment by reneebell** [comment]
perfect - thank you!

**Comment by jaredh159** [comment]
Released in 6.3.0.
