### ISSUE TITLE
Responsive Buttons

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#221]
Buttons, reimagined for a responsive world.

**Comment by lalunecreative** [comment]
Additions from P5:

- Icon option (left or right side of text)
- Ease animation option
- Fade in (from top, bottom, left, right etc)
- Allow to be thrown into the content row

**Comment by lalunecreative** [comment]
Hey @meatwad5675 - https://github.com/netrivet/prophoto-issues/issues/318 too. Active option for buttons was a request way back for 5 too. Maybe could squeeze it in since we're not launching until the 15th now for that milestone?
