### ISSUE TITLE
Responsive Call To Action Items

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#223]

**Comment by benjamintennant** [comment]
+1 Susana Torralbo - wants social sharing option like used to be in the call to action

**Comment by benjamintennant** [comment]
+1 Mischa Bolton + wants Facebook sharing options below each post

**Comment by lalunecreative** [comment]
Could go with this - https://github.com/netrivet/prophoto-issues/issues/312

**Comment by danjonlam** [comment]
+1 Peter Van Der Lingen - 140958, wants Facebook like button

**Comment by benjamintennant** [comment]
+1 Kathy Smith - wants call to action, fb, google plus.

**Comment by benjamintennant** [comment]
+1 Guido Grauer

**Comment by benjamintennant** [comment]
+1 Israel Arredondo, ticket 141632 wants Facebook like button

**Comment by benjamintennant** [comment]
+1 Andee McDonald - ticket 2792 wants a convenient way to make social media buttons

**Comment by postmastersteve** [comment]
+1 Gustavo Pozo Luque ticket 141876

**Comment by madeyouswoone** [comment]
Totally down for this! The ability to add tiles for social media icons would be stellar!

**Comment by theresavs** [comment]
+1 Need this yesterday

**Comment by benjamintennant** [comment]
+1 Susana Toleda - from feedback - wants sharing options
