### ISSUE TITLE
Pinterest pinning of individual site images

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#229]
Customizeable images that appear when you hover over individual images, to "pin" them on Pinterest.

**Comment by benjamintennant** [comment]
+1 Susana Torralbo #1909

**Comment by benjamintennant** [comment]
+1 Tessa Satake ticket 2579

**Comment by benjamintennant** [comment]
+1 Yvette James ticket 2723

**Comment by bdvphoto** [comment]
+1

**Comment by danjonlam** [comment]
+1 Shelly Suetta 140888

**Comment by benjamintennant** [comment]
+1 Sarah Jones - 141864

**Comment by postmastersteve** [comment]
+1 Kaley Diaz ticket 2913

**Comment by benjamintennant** [comment]
+1 Susana Toleda from feedback

**Comment by danjonlam** [comment]
+1 Naomi Figueroa 3280

**Comment by postmastersteve** [comment]
+1 Janice Morse ticket 143328

**Comment by postmastersteve** [comment]
+1 Steffen Harris ticket 143266

**Comment by postmastersteve** [comment]
+1 Danny Useche ticket 143425

**Comment by postmastersteve** [comment]
+1 Aysegul Sanford ticket 143665

**Comment by benjamintennant** [comment]
+1 Katrina Barrow ticket 3495 - pin it plugins only working on some images.

**Comment by northfolkco** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Amanda ticket 3539

**Comment by danjonlam** [comment]
+1 Jacob 3492

**Comment by danjonlam** [comment]
+1 Meredith Bernard 2921

**Comment by danjonlam** [comment]
+1 Kaley Diaz 144044

**Comment by postmastersteve** [comment]
+1 Reesha Almeida Coutinho ticket 144608

**Comment by postmastersteve** [comment]
+1 Michelle Butler ticket 144659

**Comment by postmastersteve** [comment]
+1 Jared Jones ticket 3801

**Comment by benjamintennant** [comment]
+1 kenny Nakai ticket 3858 - also mentions that pinterest extension cannot find the srcset images

**Comment by benjamintennant** [comment]
+1 Vanessa Pena

**Comment by benjamintennant** [comment]
+1 Megan Wynn ticket 3897

**Comment by danjonlam** [comment]
+1 Maura Chick ticket 145042

**Comment by benjamintennant** [comment]
+1 Buddie Albritton ticket 144819

**Comment by postmastersteve** [comment]
+1 Danai Athanasoula ticket 145474

**Comment by benjamintennant** [comment]
+1 Tina ticket 3968

**Comment by danjonlam** [comment]
+1 Heather O\'Brien ticket 145548

**Comment by danjonlam** [comment]
+1 Jessica Garzella ticket 145607

**Comment by danjonlam** [comment]
+1 Castle and Cubby ticket 145665

**Comment by postmastersteve** [comment]
+1 Tim Chesney ticket 146274

**Comment by jaredh159** [comment]
Completed in `6.11.0`.
