### ISSUE TITLE
Assorted Grid Enhancements

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#231]
Text length control, background color overrides (for overlay style), text-alignment, comments-count, and more...

**Comment by lalunecreative** [comment]
More layout options/animations.

**Comment by lalunecreative** [comment]
Vertical alignment of grid item text needs to be added.

**Comment by lalunecreative** [comment]
Remove the ratio if we can. It's just annoying in responsive. They never size the content like I feel like they should in a responsive environment with the idea that we're stuck to a ratio for a grid item. The custom sizes are all built in already so I just don't understand it. If it's not set EXACTLY right the content always gets cut off or doesn't fit right because of the ratio setting.

**Comment by lalunecreative** [comment]
Read more button probably needs to be added with this as well.
#297

**Comment by benjamintennant** [comment]
+1 from Bruce (https://prophoto6.zendesk.com/agent/tickets/1488) for ability to disable excerpt text on rollover grids like already possible for text below grids

**Comment by benjamintennant** [comment]
+1 from Kelly Jones #1605 asking for the ability to upload an image as the grid background

**Comment by benjamintennant** [comment]
+1 from Renee Bell wanting the to edit excerpt length for excerpt grids

**Comment by benjamintennant** [comment]
+1 for vertical alignment of rollover text from David in #1789

**Comment by lalunecreative** [comment]
+ ability to make the grid load random/ascending/descending for the different grid types.

**Comment by benjamintennant** [comment]
Jessica Shepard - ability to remove image count for galleries grid for rollover grids. It's already an option for text below grids.

**Comment by benjamintennant** [comment]
+1 Courtney Keim - vertical centering of text on rollover style

**Comment by benjamintennant** [comment]
+1 Joseph Lichstein - ability to remove excerpt text with checkbox for both dropdown and rollover styles

**Comment by jaredh159** [comment]
+1 Kati #2519

**Comment by JenniferClare** [comment]
The ability to make them as pretty as this on roll over... eventually pretty please!
http://www.paulaohara.com/blog/

**Comment by postmastersteve** [comment]
+1 Jeff Ascough ticket 141802
grid excerpt text length control

**Comment by postmastersteve** [comment]
+1 Joseph Sarkodie ticket 2989
wants hover color/fade for _text below_ style
maybe we can allow users to create grid styles like they can create gallery styles?

**Comment by benjamintennant** [comment]
+1 Sara Harper wants the ability to remove excerpt text from excerpt grids. Currently that option is in available for only text below style grid embeds.

**Comment by postmastersteve** [comment]
+1 Elon Reynolds ticket 3050
hide grid excerpt text & read more link

**Comment by benjamintennant** [comment]
+1 Jared Knetzer ticket 142917
wants to remove gallery image number count on rollover style girds

**Comment by lalunecreative** [comment]
+1 for that ability to remove the gallery image number count on gallery rollover grids. That was a pain in 5 too.

**Comment by postmastersteve** [comment]
+1 Megan Wynn ticket 3236
wants to hide excerpt text for the blog (using excerpt grids w/text-below style)

**Comment by lalunecreative** [comment]
Ability to upload a background image to both grid types.

**Comment by benjamintennant** [comment]
+1 matthew hicks ticket 143314 - wants to remove excerpt text from rollover grids

**Comment by benjamintennant** [comment]
+1 Ryan Anastor ticket 143693 - wants to remove excerpt text from excerpt grids

**Comment by benjamintennant** [comment]
+1 WISAM MAHMOOD ticket 144043 wants to override rollover overlay background color like you could with ProPhoto 5 -
https://cloud.githubusercontent.com/assets/12831291/16955102/74091dde-4da1-11e6-896a-541c1a320a9c.png

**Comment by postmastersteve** [comment]
+1 Jared Jones ticket 3756
wants to remove gallery count on grids

**Comment by lalunecreative** [comment]
Option to turn off the "read more" link on individual grid widgets. This is in case you have it set globally, but don't want it set on a certain grid in a particular section.

**Comment by postmastersteve** [comment]
+1 Anne Paar ticket 3793
wants to remove grid excerpt text for main excerpts option area

**Comment by postmastersteve** [comment]
+1 Vinger Elliot ticket 144968
wants to set a grid to open links in a new tab (for example, a grid widget linking to portfolio galleries)

**Comment by lalunecreative** [comment]
Border with options (color, size, etc) that shows on hover for Overlaid style grids.

**Comment by lalunecreative** [comment]
Retina option for read more graphic image upload

**Comment by benjamintennant** [comment]
+1 Leslie Blasgen ticket 145874 wants the option to remove the number of images for galleries grid thumbnails for rollover grids. The option already exists for text below grids.

**Comment by jaredh159** [comment]
Closing, because this ticket was a giant, unorganized grab bag.  All requests and comments captured and transferred to these new tickets:

https://github.com/netrivet/prophoto-issues/issues/674
https://github.com/netrivet/prophoto-issues/issues/675
https://github.com/netrivet/prophoto-issues/issues/676
https://github.com/netrivet/prophoto-issues/issues/677
https://github.com/netrivet/prophoto-issues/issues/678
https://github.com/netrivet/prophoto-issues/issues/679
https://github.com/netrivet/prophoto-issues/issues/680
