### ISSUE TITLE
WPML multi-language plugin support

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#235]

**Comment by andreabagnasco** [comment]
hello - really (really!) looking forward for P6 to support WPML. Is there an estimated date when this will happen? Is there a way to beg you to provide this support asap? :) ... thanks!

**Comment by aleghedina** [comment]
Hi guys, I'm using WPML for my web site and I'm ready to goto version 6 of prophoto, do you know if is it possible now, do I need to wait until is ready the compatibility?
thank you Alessandro

**Comment by ciprianimike** [comment]
support for WPML is really important , can you tell us when you think it will be available?

**Comment by jaredh159** [comment]
@ciprianimike, @andreabagnasco, @aleghedina we know it's really important, and we're committed to doing it.  It's on the [roadmap](https://www.prophoto.com/p6-road-map/) and our estimated completion date is early June. Thanks for your patience.

**Comment by aleiase** [comment]
Hello - just wanting to point out how urgent WPML support is for us international P6 adopters - a lot of our business is done with foreign clients and therefore a bilingual version of our website is of utmost importance. Please consider anticipating this feature vs current schedule. Thanks, Alessandro

**Comment by lalunecreative** [comment]
@jaredh159 this probably needs to be moved back to june in place of or addition to something.

**Comment by benjamintennant** [comment]
+1 Juerg Wurzer ticket 2561

**Comment by postmastersteve** [comment]
+1 Fabian Bischof ticket 141482

**Comment by DoctibPhoto** [comment]
+1

**Comment by jaredh159** [comment]
Closed by `6.9.0`
