### ISSUE TITLE
Responsive Instagram widget

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#241]

**Comment by benjamintennant** [comment]
+1 Matthias from ticket #1701

**Comment by benjamintennant** [comment]
+1 Aaron from ticket 1885

**Comment by benjamintennant** [comment]
+1 Jenny Gildea #2191

**Comment by benjamintennant** [comment]
+1 Katrina Barrow #2409

**Comment by postmastersteve** [comment]
+1 Agnes Colombo ticket 2590

**Comment by danjonlam** [comment]
+1 Erica 2737

**Comment by danjonlam** [comment]
+1 Andee McDonald 2940

**Comment by postmastersteve** [comment]
+1 Aamie Cush ticket 142536

**Comment by northfolkco** [comment]
+1000 NF

**Comment by danjonlam** [comment]
+1 Amy Haberland 143028

**Comment by postmastersteve** [comment]
+1 Megan ticket 3235

**Comment by benjamintennant** [comment]
+1 Nada ticket 3300

**Comment by postmastersteve** [comment]
+1 Jennifer James ticket 143370

**Comment by danjonlam** [comment]
+1 Ashley Reece 143865

**Comment by benjamintennant** [comment]
+1 Cassandra Nichos from feedback

**Comment by benjamintennant** [comment]
+1 Katie Leverenz ticket 144066

**Comment by postmastersteve** [comment]
+1 Marita Gvalda ticket 144303

**Comment by postmastersteve** [comment]
+1 Dan Macklin ticket 145232

**Comment by danjonlam** [comment]
+1 Grant Kennedy ticket 145252

**Comment by postmastersteve** [comment]
+1 Carolin Da Silva Nunes ticket 145291

**Comment by postmastersteve** [comment]
+1 Lindsey Harwath ticket 145411

**Comment by danjonlam** [comment]
+1 Frances Huang ticket 145460

**Comment by danjonlam** [comment]
+1 Michelle Able ticket 145808

**Comment by danjonlam** [comment]
+1 Jason Talley ticket 145824

**Comment by danjonlam** [comment]
+1 Kenneth Black ticket 146001

**Comment by benjamintennant** [comment]
+1 Monique Serra ticket 146823

**Comment by jaredh159** [comment]
Released in `6.13.0`
