### ISSUE TITLE
Grid excerpts rendering plugin shortcodes

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#260]
![screen shot 2016-01-27 at 8 49 11 am](https://cloud.githubusercontent.com/assets/7050938/12616973/9ad9217e-c4db-11e5-90ec-4ace41f46c20.png)

**Comment by meatwad5675** [comment]
Not sure if something changed here or what, but now I'm getting a json parse error for a similar grid because the shortcode is getting parsed, which is adding unslashed html tags to the grid json.
