### ISSUE TITLE
Property violations in comment customizations

### ISSUE THREAD

**Issue by brianium** [netrivet/prophoto-issues#27]
Either need to make these optional (which it seems they are) or supply a value :tongue: 

![screen shot 2015-11-06 at 9 28 57 am](https://cloud.githubusercontent.com/assets/636651/10999236/eb228cd2-8468-11e5-936e-4ffea8becc0e.png)

**Comment by brianium** [comment]
Error is thrown when viewing customizations for comment bodies

**Comment by jaredh159** [comment]
Fixed in https://github.com/netrivet/prophoto/pull/483.
