### ISSUE TITLE
When uploading photos via P6 (drag n drop) permissions are set to 700

### ISSUE THREAD

**Issue by dtsiapas** [netrivet/prophoto-issues#276]
When uploading photos via P6 ,eg. drag n drop photo as background, file permissions are set to 700.

**Comment by dtsiapas** [comment]
Anyone please?

**Comment by brianium** [comment]
@dtsiapas I don't think we do anything with permissions as part of the upload process. Permissions should really just reflect the permissions of the `upload_tmp_dir` set in PHP.

What sort of behavior are you expecting?

Thanks for opening the issue :)

**Comment by dtsiapas** [comment]
@brianium  Problem solved. I changed in suphp.conf the umask to 0022 from 0077

**Comment by brianium** [comment]
@dtsiapas glad it's solved. Let me know if you need help with anything else.
