### ISSUE TITLE
Favicon upload

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#281]
+1 Brian Clary

**Comment by lalunecreative** [comment]
+1 From me, sent a ticket about it yesterday.

**Comment by TimKamppinen** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Karen Linton #1713

**Comment by bdvphoto** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Ginny Haupert https://prophoto6.zendesk.com/agent/tickets/1870

**Comment by benjamintennant** [comment]
+1 Melisa Ford #1903

**Comment by benjamintennant** [comment]
+1 Joseph #1607

**Comment by benjamintennant** [comment]
+1 DaJuan Jones ticket 2353

**Comment by benjamintennant** [comment]
+ Fritz, ticket 2302

**Comment by benjamintennant** [comment]
+1 Julie Copestake ticket 2438

**Comment by danjonlam** [comment]
+1 Jennifer Gentry 140889

**Comment by jaredh159** [comment]
Done and released in `6.2.0`.
