### ISSUE TITLE
Toggle visibility of nested items in vertical menus

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#282]
Click/touch on a primary menu item with children to slide-down and slide-up the child menu

+1 Kenny Nakai

**Comment by benjamintennant** [comment]
+1 from Natasha Craven on https://prophoto6.zendesk.com/agent/tickets/1611. She is looking for vertical menu flyouts or dropdowns.

**Comment by benjamintennant** [comment]
+1 from Jennifer Clare on https://prophoto6.zendesk.com/agent/tickets/1648

**Comment by postmastersteve** [comment]
+1 Alana Franke ticket 1778

**Comment by northfolkco** [comment]
+1

**Comment by danjonlam** [comment]
+1 Sarah Jone ticket 140002

**Comment by benjamintennant** [comment]
+1 Fritz ticket 2303

**Comment by postmastersteve** [comment]
+1 Kathy Smith ticket 2633

**Comment by postmastersteve** [comment]
+1 Mallory Haren ticket 141596

**Comment by benjamintennant** [comment]
+1 Heather Beck ticket 142191

**Comment by benjamintennant** [comment]
+1 Harold Blair ticket 3445

**Comment by benjamintennant** [comment]
+1 Brian Rickey ticket 143685

**Comment by northfolkco** [comment]
Has this one got a timeframe? I would like to rescind my +1 and raise a +1m 💃

**Comment by danjonlam** [comment]
+1 Susan Van Der Veen ticket 144273

**Comment by postmastersteve** [comment]
+1 Carla ticket 3739

**Comment by postmastersteve** [comment]
+1 Ashley Jankowski ticket 3767

**Comment by benjamintennant** [comment]
+1 Yvette Griffith feedback #145009

**Comment by jaredh159** [comment]
Completed in `6.11.0`.
