### ISSUE TITLE
Custom font uploading

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#292]
Ability to upload a fontsquirrel-style font kit for use in ProPhoto 6 font styles.

+1,000,000

**Comment by brianium** [comment]
+1,000,001

**Comment by lalunecreative** [comment]
+1,000,002.

**Comment by jaredh159** [comment]
+1 Rhonda Stark

**Comment by jaredh159** [comment]
+1 Benjamin Thorn
