### ISSUE TITLE
Add clickable "read more" links to excerpts

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#297]
Both standard and grid, likely.  Probably a good first pass would be just to allow text-based links, with the text customizable.

**Comment by chavim** [comment]
+1 Chavi Malka

**Comment by jaredh159** [comment]
Also, this would involve getting rid of the WordPress default `[...]` on standard excerpts, which Matt Hudson hates with the wrath of a thousand scorned lovers.

**Comment by brianium** [comment]
:heart_eyes: :angry:

**Comment by lalunecreative** [comment]
+ Eleventy Billion. Those brackets are the bane of my existence since grids were introduced. Because nobody anywhere has ever said[...]

**Comment by benjamintennant** [comment]
+1 Renee Bell #1664 for tiles/image for read more link in excerpt grids

**Comment by benjamintennant** [comment]
+1 Susana Toralbo #1911 - wants to use tile for read more link on excerpts

**Comment by postmastersteve** [comment]
+1 Kelly Zugay ticket 140896

**Comment by jaredh159** [comment]
Done in `6.2.0`.

**Comment by lalunecreative** [comment]
The lovers are scorned no longer! Thank you my Liege!
