### ISSUE TITLE
1/2 pixel rendering issue in galleries in Safari

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#306]
A gallery with something butted against the bottom will show a 1px line at the bottom at some display widths.  To replicate, insert a gallery with a white background into a site that has entirely black backgrounds, open in Safari, and start resizing the window.

When calculating the width of each slide, and calculating the translation, we need to round up to a whole pixel or jankiness ensues.

**Comment by lalunecreative** [comment]
Grids still do this too.

**Comment by meatwad5675** [comment]
+1 Grant Kennedy

**Comment by postmastersteve** [comment]
+1 Rory Wylie ticket 149888

**Comment by postmastersteve** [comment]
+1 Carolyn Harris ticket 150265
not in Safari - confirmed in Chrome on my Mac, here:
http://www.carolynlharris.com/2016/11/04/worlds-narrowest-street/

**Comment by benjamintennant** [comment]
+1 Viktor Isaak ticket 159382 - voicing a complaint from his clients about the 1/2 or whole pixel sliver sometimes visible on bound galleries.

**Comment by brianium** [comment]
@benjamintennant @postmastersteve @danjonlam - next time you guys come across an instance of this can you let me know? This one is hard to reproduce, so it would help to see the issue in the wild.

**Comment by lalunecreative** [comment]
@brianium I can send you something. I've seen it in some of our sites. Give me a little while and I scoop it out.

**Comment by brianium** [comment]
@lalunecreative awesome! Much appreciated brajjer.

**Comment by lalunecreative** [comment]
So this isn't only effected by Safari, and or the method that Matt showed to reproduce, and when I've seen it it's been in some grid instances, and usually always sliders. For sliders though, that 1px is showing the previous/next image which happens to be dark. It's harder to see when it's not in this instance.

https://designs.pro.photo/ivory/slider-gallery/

![slider1](https://cloud.githubusercontent.com/assets/17013471/23572120/2513906a-002a-11e7-8c8b-25e9f4af0587.jpg)

**Comment by lalunecreative** [comment]
And for grids - 
![there](https://cloud.githubusercontent.com/assets/17013471/23572283/39a521a0-002b-11e7-9a89-6f60e1068208.jpg)

https://designs.pro.photo/ivory/blog/

**Comment by brianium** [comment]
I think this is fixed in galleries. I'm going to close this issue and open a new one for the grid issue.
