### ISSUE TITLE
Add column border customizations

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#314]
Maybe just left/right, but those at least.  A really common and compelling use case would be a user who has a content column, and a column next to it functioning like a traditional sidebar.  Having a line to separate the two would seem like a fairly important thing to be able to do.

**Comment by lalunecreative** [comment]
+1

**Comment by theresavs** [comment]
+1 since 5 allows this

**Comment by danjonlam** [comment]
Customer +1 - https://prophoto6.zendesk.com/agent/tickets/1964

**Comment by benjamintennant** [comment]
+1 Courtney Keim

**Comment by postmastersteve** [comment]
+1 Kaley Diaz ticket 2913
Border for columns - particularly for sidebars

**Comment by madeyouswoone** [comment]
+1 Swoone

**Comment by jaredh159** [comment]
Completed in `6.10.0`
