### ISSUE TITLE
Base template description should be editable

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#320]
Maybe the name too, but at least the description.  We need this because you can change the name of the design, but the base description always uses the name of the design when it was created.  So, you could be using the "Crafted" design as your starter, spend a long time customizing it, change the design name in the manage designs screen to "Sasquatch", and then your "Sasquatch" design still has the base template description of "This is the base template for your 'Crafted' design."

**Comment by theresavs** [comment]
There was a bug where the name actually changed for me. It happened again so I was able to change it back.
