### ISSUE TITLE
Give control for widget visibility at breakpoints

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#321]
This is already on our backlog internally, but we've had beta tester request for it as well, so I wanted a public issue as well.

**Comment by jaredh159** [comment]
+1 Matt Hudson

**Comment by northfolkco** [comment]
+1 Northfolk

**Comment by jaredh159** [comment]
+1 Dawn Alderman

**Comment by melissalove** [comment]
+ 1 Would love this.
