### ISSUE TITLE
Support max-width for images widget

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#326]
To better handle retina and other high-dpi devices for smaller images like icons.

**Comment by lalunecreative** [comment]
+1000. Small images look like dookie on retina.

**Comment by dawnalderman** [comment]
+1

**Comment by lalunecreative** [comment]
Ugh small images look so bad...the more I customize and look on iPad, the worse I cringe. +1,000,000

**Comment by theresavs** [comment]
+1
