### ISSUE TITLE
Expose control for column stacking switch point

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#328]
Currently, at a certain viewport breakpoint, all the "medium" breakpoint, *all* columns change to `100%` width, thus stacking one on top of each other. This would expose an option for rows to have the full-stacking behavior kick in at a smaller screen size, preserving side-by-side columns for medium-sized devices like smaller laptops and tablets.

or, refer to this impeccably lucid illustration @meatwad5675 made:

![img_5775_720](https://cloud.githubusercontent.com/assets/7050938/13058570/0dd2de48-d3f2-11e5-9109-91f4786baa6a.jpg)

**Comment by lalunecreative** [comment]
That's some Einstein looking development drawing right there. Good thing someone understands it. lol

**Comment by brianium** [comment]
It really just boils down to this:

![](http://www.quantum-immortal.net/math/images/areaeqn.png)

**Comment by lalunecreative** [comment]
Ohhh yeah I totally understand that!

Ok not really but...

![hee1i](https://cloud.githubusercontent.com/assets/17013471/13059442/5adbd6f0-d3e7-11e5-9415-695e50f27e4f.jpg)

**Comment by brianium** [comment]
lol
