### ISSUE TITLE
Under construction mode doesn't work

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#331]
It should be made to work, or at least temporarily removed rather than sitting there on a throne of lies.

**Comment by jaredh159** [comment]
+1 Matt Hudson

**Comment by lalunecreative** [comment]
So the problem I've run into with this is that unless you change old links while you set it up the way I had it (where the homepage is set to a template) they still have access to the site.

So the template thing works well, it allows for creating your own construction page, but it needs to work to disable the site like before so people can't get access to basic areas while working like the mobile menu, and any pages that were previously linked.

**Comment by lalunecreative** [comment]
Plus...not sure if anyone has thought of this. You can't test drive mode P6 to a P6 design. lol. So what happens when someone wants to work on their site down the road and not have anyone access to it?

**Comment by jaredh159** [comment]
@lalunecreative if you wanted to use a special template as an "under construction mode" you should be able to use template custom css to totally hide the mobile hamburger menu.

Regarding your second question -- when we have some time, it will be very easy to allow a user to customize and preview a P6 design while showing a different P6 design on the site front.  Our new architecture makes that a breeze, we just have to get around to making that a possibility.

**Comment by lalunecreative** [comment]
Then that's definitely the solution. Test drive mode for a P6 design. That way you don't have to worry about disabling anything at all. 

I css'd out the horizontal menu and left the mobile one with just the home page. It kinda lets people see what a P6 mobile design looks like so I left it.

**Comment by lalunecreative** [comment]
There still might be some issues with page updating now that I think about it.  Not sure what the solution would be. When you update a page in test drive mode that's already being shown on the site it's going to update it so people can see it on the regular site too. At least with the content area. Not sure a fix for that.

**Comment by caryn-photog** [comment]
I was just test driving P6 on my desktop and wanted to see my P5 site on my iPhone and it brought up the P6 version I am currently working on. YIKES! Leaving P6 test mode ASAP since I have clients actively on my site all the time  :(

**Comment by jaredh159** [comment]
@caryn-photog you must have been logged in on your phone, right?  Other users should not have seen P6 unless they are logged in as an admin.  I've not seen an instance yet where the test-drive plugin was showing the test-driven theme to non logged in users.  But if you're certain it was, send us a support request so we can troubleshoot.  Thanks!
