### ISSUE TITLE
Add admin "labels" for widgets

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#332]
To make it much easier, at a glance, looking at the customizer layout, to see what the widgets are.  For instance, an images widget being used as the logo, could be labeled "logo". Menus could be labeled in instructive ways.  This would really be useful for designers selling designs, because it would immediately orient the user as to where they should go to edit things, instead of having to guess and click around.

We can probably do some more work with various widget types, dialing in how to preview their title/label, based on type.  The goal should be that the whole layout becomes more comprehensible at a glance, from a high level, and that new users of a design can orient themselves quickly.

**Comment by jaredh159** [comment]
+1 Melissa Love

**Comment by lalunecreative** [comment]
+1 asked for this ages ago in P5. Hope it makes it!

**Comment by northfolkco** [comment]
Could you also add making the blocks collapsible so its cleaner and easier for a buyer to target the intended block?

**Comment by melissalove** [comment]
+1

**Comment by jaredh159** [comment]
+1 Danielle McCarty
