### ISSUE TITLE
Center grids not using full parent element width

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#333]
There are times when a ProPhoto 6 responsive grid does not take up the full width of it's containing element.  When this is the case, it usually seems desirable that the grid would be centered within the container, instead of left-aligned.

**Comment by jaredh159** [comment]
+1 Dawn Alderman

**Comment by benjamintennant** [comment]
+1 for sure. The grid item should center when widgets in that column are set to center. This looks especially bad because the grid title does center.

**Comment by postmastersteve** [comment]
+1 Giovanni Gori ticket 3088

**Comment by postmastersteve** [comment]
+1 Joseph Sarkodie ticket 142644

**Comment by danjonlam** [comment]
+1 Renee Bell 3033

**Comment by postmastersteve** [comment]
+1 Philippa Lurcock ticket 3442

**Comment by danjonlam** [comment]
+1 Leslie Vega #145478

**Comment by danjonlam** [comment]
+1 Claire Brennan ticket 145513

**Comment by postmastersteve** [comment]
+1 Anna Wisjo ticket 145558

**Comment by danjonlam** [comment]
+1 Grace Laird ticket 145841

**Comment by danjonlam** [comment]
+1 Kenneth Black ticket 146001

**Comment by jaredh159** [comment]
Completed in `6.10.0`
