### ISSUE TITLE
NextGen Gallery plugin compatibility problem

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#335]
For some reason, when NextGen is active, we lose our enqueued `underscore.js` file, which breaks lots of things.  They do a ton of whacky stuff with rewriting and output buffering the footer scripts, so I'm fairly certain this is their fault, but it still needs to be looked into.

The NextGen class that is causing the problems is: `C_Photocrati_Resource_Manager`

**Comment by jaredh159** [comment]
Also, a quick test of `twentysixteen` with a simple call to `wp_enqueue_script('underscore')` did not manifest the same issue, so it's some interop thing with ProPhoto and NextGen specifically, not a simple huge whoops on their part, since it doesn't manifest on the wp default theme in my initial smoke test.

**Comment by jaredh159** [comment]
+1 Claudia (she had same problem)

**Comment by TimKamppinen** [comment]
When NextGen Plus is enabled, every time I try to save a change in the customizer I get the "Another active session has been detected" message.  When I takeover it throws me back to my top level template and none of my changes have been saved.  I'm able to go back and make the changes, but then when I try to change something else it happens again.
