### ISSUE TITLE
Customize gallery thumbstrip behavior

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#339]
* set thumbstrip to *not* overlay
* thumbnail size
* thumbnail border
* thumbstrip bg color
* thumbstrip paging arrows
* thumbstrip position (top or bottom *maybe sides?*)

**Comment by jaredh159** [comment]
+1 Jennifer Clare

**Comment by lalunecreative** [comment]
+1

**Comment by meatwad5675** [comment]
@lalunecreative Could you clarify what you mean by animations?  Besides sliding the thumbstrip up/down or fading it in/out, and then sliding thumbnail pages left/right, what kind of animations would you want to see there?

**Comment by lalunecreative** [comment]
Thumbstrip could fade in/out, ease in/out on clicks, animate in from the sides, top, bottom, etc etc. Sooo many neat options.

**Comment by ThomasGeist** [comment]
Thumbstrip behavior on iPad still seems problematic. It sticks and would not slide down.
