### ISSUE TITLE
Sticky blocks (menus)

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#348]
Allow at least blocks (maybe rows) to be made "sticky" -- to stay fixed at the top of the viewport, or stick when they hit the top of the viewport.  This would make it very easy to create a sticky menu effect like P5 supports, by making a block sticky with one row and one column, containing a horizontal menu.

**Comment by benjamintennant** [comment]
+1 Mayda Mason https://help.prophotoblogs.com/tickets/137673

**Comment by benjamintennant** [comment]
+1 Jennifer Madino https://prophoto6.zendesk.com/agent/tickets/1485

**Comment by postmastersteve** [comment]
+1 Heidi Howard ticket 1779

**Comment by postmastersteve** [comment]
It may be good to support sticky columns, too, so that layouts with a menu in a sidebar can remain stuck while scrolling a content column. This may not be possible until full-height columns are supported, though...

**Comment by benjamintennant** [comment]
+1 Jessica Shepard #1898
