### ISSUE TITLE
Add at least 2 free, included P6 designs

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#349]

**Comment by karliehawkinsphotography** [comment]
hopefully there will be more free template designs. PP5 had 14 as a hook. i purchased PP6 because it was the new one coming out, i expect it to have at least a few more designs to choose from for my purchase. will there be more than 2 template designs coming out for PP6? it would be a big slap to the face if not.

**Comment by jaredh159** [comment]
@karliehawkinsphotography 2 is just the bare minimum to start with to come out of beta.  We actually are pretty sure that by next week we will be shipping with 5, and that number will continue to grow.  It took us years to build up to 14 free designs for the fixed-width versions of ProPhoto, so this won't happen overnight.  But we'll start with 5 and try to add a new one every couple months if possible, which is similar to what we did with P5.  It did not launch with all 14.

**Comment by RHarrisP** [comment]
Just to clarify - are there *any* free/included PP6 compatible designs included as default yet?

I was reading this as if by the 19th of April we would *then* have 2 initial, ready made designs (meaning, making adjustments easier, rather than starting from scratch).

**Comment by jaredh159** [comment]
@RHarrisP yes, you're right, the ticket says we will have a minimum of two included designs by the end of this milestone (which we a few days behind on).  But, we already have one, and by mid-week next week we should have at least 4, and probably 5.  So, we're a tiny bit behind our timeline, but we're going to far exceed our minimum goal of 2 free included designs.

**Comment by RHarrisP** [comment]
Thanks Jared. That's great that you already have 1 included! Having 4-5 starters would be more than enough for everyone's needs too, surely. For me it's not such a big deal, as I want to get in there and customize everything, but having a starting point can be helpful just so everything "works okay" whilst you're tweaking. I think I'll have to wait until the contact form arrives first :). Thanks for the quick reply.

**Comment by reneebell** [comment]
How do we see the included designs? I cant see them in my "manage pro photo designs" section - but it has been marked as complete. thanks

**Comment by jaredh159** [comment]
@reneebell If you don't see them in your manage designs section, maybe your site isn't auto-updating correctly.  Send us a support request with your WordPress and FTP login so we can look into it.
