### ISSUE TITLE
Gallery thumbnail/grid display

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#351]
Not the same as gallery thumbstrip navigation (already possible). This is rather the ability to view a gallery as a grid of thumbnails, either cropped, or masonry.  This is similar to P5's lightbox gallery, except it wouldn't pop up the old lightbox-style modal.  Instead it could not pop-up at all when clicked, or popup a full-window view, or popup a fullscreen view.

**Comment by TimKamppinen** [comment]
PLEASE give the option for horizontal rows in addition to pinterest-style (columns) when doing a masonry gallery.  Columns are terrible if you want to have any sort of chronological flow to a set of images.

**Comment by postmastersteve** [comment]
+1 Courtney Horwood ticket 1765

**Comment by postmastersteve** [comment]
+1 Carrie ticket 2234

**Comment by postmastersteve** [comment]
+1 Thomas Geist ticket 2136

**Comment by postmastersteve** [comment]
+1 Juliana Redondo ticket 2055

**Comment by postmastersteve** [comment]
+1 Mark Beaumont ticket 2188

**Comment by postmastersteve** [comment]
+1 Christine Neely ticket 2216

**Comment by postmastersteve** [comment]
+1 Courtney Horwood ticket 1765

**Comment by postmastersteve** [comment]
+1 Justin Bahr ticket 1328

**Comment by postmastersteve** [comment]
+1 Rhonda Stark ticket 399

**Comment by benjamintennant** [comment]
+1 Dajuan Jones ticket 2283

**Comment by bdvphoto** [comment]
+1

**Comment by danjonlam** [comment]
+1 Fritz Liedtke ticket 140095

**Comment by benjamintennant** [comment]
+1 Fritz photo ticket 2301

**Comment by danjonlam** [comment]
+1 Rebecca Pattinson 140001

**Comment by tamaraCda** [comment]
what @TimKamppinen said above.  Please, please, please!

**Comment by danjonlam** [comment]
+1 Ann O'Neill Deal ticket 2412

**Comment by danjonlam** [comment]
+1 Angela Mohney ticket 1003

**Comment by benjamintennant** [comment]
+1 Jenny Gildea ticket 2420

**Comment by danjonlam** [comment]
+1 Carina Dunmore ticket 140618

**Comment by benjamintennant** [comment]
+1 Mike Moreland ticket 1545

**Comment by danjonlam** [comment]
+1 Beckie ticket 2466

**Comment by benjamintennant** [comment]
+1 Rebecca Pattinson says, "I want them, I need them!"

**Comment by postmastersteve** [comment]
+1 Amy Verduyn ticket 141172

**Comment by benjamintennant** [comment]
+1 Jeff from ticket 2647

**Comment by danjonlam** [comment]
+1 Crystelle Carrick 141334

**Comment by danjonlam** [comment]
+1 Cory Okeefe 141578

**Comment by JenniferClare** [comment]
Nearly there yet?!?!

**Comment by brianium** [comment]
Being worked on right now :)

**Comment by postmastersteve** [comment]
+1 Nadine Püchl ticket 2800

**Comment by benjamintennant** [comment]
+1 Erica Robinson ticket 2770

**Comment by benjamintennant** [comment]
+1 Andrea Kuntz ticket 2835

**Comment by postmastersteve** [comment]
+1 Michelle Yam ticket 2769

**Comment by benjamintennant** [comment]
+1 Gavin Wyatt ticket 141871

**Comment by danjonlam** [comment]
+1 Andee McDonald 2873

**Comment by postmastersteve** [comment]
+1 Katie Campbell ticket 142122

**Comment by benjamintennant** [comment]
+1 Susan DeLoach ticket 142136

**Comment by benjamintennant** [comment]
+1 Kylie Mitchell - she also wants us to know she hopes to still have an image number option like we had with lightbox galleries.

**Comment by northfolkco** [comment]
+1 Northfolk.

Will it not be at all possible to get it like the lightbox gallery?

**Comment by postmastersteve** [comment]
+1 Abigail Taylor ticket 142353
