### ISSUE TITLE
Numbered posts pagination

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#352]

**Comment by danjonlam** [comment]
Possibility to add infinite scrolling option as well? (Per customer requests)

**Comment by lalunecreative** [comment]
I would actually love all those old options for the pagination (loading, infinite scrolling, numbers, tiles, etc) It definitely adds variety to a spot that has none right now.

**Comment by benjamintennant** [comment]
+1 infinite scrolling for grid excerpts - Riley Tsang #1688

**Comment by postmastersteve** [comment]
+1 Infinite scrolling, Jon Hwang ticket 142593

**Comment by postmastersteve** [comment]
+1 Infinite scrolling, Cindy Boisvert ticket 143251

**Comment by danjonlam** [comment]
+1 Ling Wang ticket 144958

**Comment by danjonlam** [comment]
+1 Laura Kent ticket 146265 - infinite scrolling

**Comment by danjonlam** [comment]
+1 Linda Ramdane ticket 147483

**Comment by postmastersteve** [comment]
+1 Dennis ticket 147909
also would like new « and » double chevron buttons to shoot directly to the very first or last page of posts, similar to the WordPress admin provides:

![aaprophoto](https://cloud.githubusercontent.com/assets/275742/18915795/24527f00-8560-11e6-9d98-8f7d7e843a59.JPG)

**Comment by benjamintennant** [comment]
+1 Israel Arredondo ticket 148317 - wants pagination as shown here. 
![2016-10-05_09-34-37](https://cloud.githubusercontent.com/assets/12831291/19115196/05db1206-8adf-11e6-8151-a61135d5db03.jpeg)

**Comment by benjamintennant** [comment]
+1 Paula Román ticket 149132

**Comment by postmastersteve** [comment]
+1 PoLin LAI ticket 149582
Infinite scrolling

**Comment by postmastersteve** [comment]
+1 Sam Rummans ticket 149583
Infinite scrolling or AJAX _Load More_ button

**Comment by danjonlam** [comment]
+1 Jess Burges ticket 149660 - infinite scrolling

**Comment by benjamintennant** [comment]
+1 Tina Kraemer ticket 149870 wants infinite scrolling

**Comment by postmastersteve** [comment]
+1 Greg Benz ticket 149914

**Comment by danjonlam** [comment]
+1 Diaan Wu ticket 149945

**Comment by danjonlam** [comment]
+1 Linda Ramdane ticket 150216 - use graphic for 'older posts/newer posts' text

**Comment by postmastersteve** [comment]
+1 Amanda Schoch ticket 150339
infinite scrolling

**Comment by postmastersteve** [comment]
+1 Amanda Schoch ticket 150550
Infinite scrolling

**Comment by benjamintennant** [comment]
+1 Andrew Holman ticket 152568

**Comment by benjamintennant** [comment]
+1 Jacek Kawecki ticket 153924

**Comment by benjamintennant** [comment]
+1 David Nguyen ticket 155179 for infinite scrolling

**Comment by danjonlam** [comment]
+1 Chunmin Chen ticket 156591

**Comment by postmastersteve** [comment]
+1 Piotr Dziwak ticket 157277

**Comment by danjonlam** [comment]
+1 Emilie Smith ticket 158043

**Comment by danjonlam** [comment]
+1 Pascal Landert Facebook/ticket 158564 - use graphic for previous and next post links

**Comment by postmastersteve** [comment]
+1 Josée Lamarre ticket 159200
numbered pagination for the blog pages

**Comment by danjonlam** [comment]
+1 Jaroslaw Pekala ticket 159848

**Comment by danjonlam** [comment]
+1 Sam Rowe ticket 160495 - wants control of text shown on individual post pages, i.e. "Next"/"Previous" instead of default post titles

**Comment by postmastersteve** [comment]
+1 John ticket 161850

**Comment by danjonlam** [comment]
+1 Melissa Pushelberg ticket 162286

**Comment by postmastersteve** [comment]
+1 Anaísa López ticket 162237
Infinite scrolling

**Comment by jaredh159** [comment]
Completed in `6.19.0`.
