### ISSUE TITLE
Indicate in UI that templates share widgets

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#356]
Users find this very unintuitive, and there is no UI indication that changing a widget in a child template changes it in it's parent.  We need to think of a way to communicate this.

**Comment by lalunecreative** [comment]
I agree and I think a simple solution would be to just add a active/non active icon to say whether or not it's active or not. A good idea is simply to colorize the widget icon if it is. So for a prophoto custom icon widget it has the little icon of a photo, that could be colored if it was inherited from the parent in this case.

**Comment by benjamintennant** [comment]
+1 David got confused by this in #1823.

**Comment by meatwad5675** [comment]
fixed in ff0b6146c3c0448bd39a0eae8953cc931a59c057
