### ISSUE TITLE
Hamburger icon and mobile menu controls

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#357]
Hamburger icon placement, color, size, appearance, etc.

**Comment by jaredh159** [comment]
+1 Mark Earthy

**Comment by northfolkco** [comment]
+1 Northfolk

would be nice to have the option to place next to the logo on the same line
as well

On Mon, Feb 22, 2016 at 9:57 AM, Jared Henderson <notifications@github.com>
wrote:

> +1 Mark Earthy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netrivet/prophoto-issues/issues/357#issuecomment-187265569>
> .
>



-- 

Sam & Rachel  //  Design & Branding
Website <http://www.northfolk.co/>  //  Shop <http://shopnorthfolk.co>  //
Facebook <https://www.facebook.com/northfolkco>  //  ProPhoto
<http://www.prophoto.com/designer/northfolk>

**Comment by lalunecreative** [comment]
+ 1,000

**Comment by jaredh159** [comment]
+1 Laurel Bern

**Comment by jaredh159** [comment]
Via @lalunecreative 

> #1- Hamburger icon customization (size, transparency, animation, colors, etc) 
> #2- Ability to add things like logos/buttons/social icons 
> #3 - Ability to remove/edit slideout shadow 
> #4 - Ability to switch sides (show hamburger/slideout on left or right side of browser)

**Comment by lalunecreative** [comment]
Mobile menu background color needs transparency too.

**Comment by benjamintennant** [comment]
+1 for mobile menu icon alignment options from Joseph in #1607

**Comment by benjamintennant** [comment]
+ Alana Franke wants to remove shadow for mobile menu icom

**Comment by benjamintennant** [comment]
+1 Joanie Fong ticket 2351

**Comment by brianclaryphoto** [comment]
+1

**Comment by postmastersteve** [comment]
+1 Michelle Yam ticket 2388

**Comment by benjamintennant** [comment]
+1 Steven ticket 2968

**Comment by danjonlam** [comment]
+1 Jeff 3109 - Add logo to mobile menu area

**Comment by MrJPH** [comment]
Making the whole Mobile Menu into an actual sidebar!  That can be hidden away until opened, just as the Mobile Menu is now - except, be a sidebar!  Able to be treated like any other sidebar with text, images, code, widgets, what have you!  <--->  Yes, please!  :-D

**Comment by danjonlam** [comment]
+1 Les Taylor - Ability to add social media icons directly into the mobile menu sidebar

**Comment by danjonlam** [comment]
+1 Leigh Ripps 3242

**Comment by danjonlam** [comment]
+1 Steve Bennett 143338

**Comment by postmastersteve** [comment]
+1 Elisabeth Ross ticket 143450

**Comment by danjonlam** [comment]
+1 Katherine Kolenberg ticket 144538

**Comment by danjonlam** [comment]
+1 Katelyn 3716

**Comment by benjamintennant** [comment]
+1 Noel Perrone ticket 144645 
Wants to replace the hamburger with something else that is completely his own - text or image, but have the same effect of appearing only when the mobile menu appears.

**Comment by postmastersteve** [comment]
+1 Nicole Barralet ticket 144757

**Comment by postmastersteve** [comment]
+1 Jackson Eddy ticket 145057
style and placement

**Comment by benjamintennant** [comment]
+1 Abbeygail Elaine ticket 3885, color, size, background

**Comment by danjonlam** [comment]
+1 Danai Athanasoula ticket 146103 - Have mobile menu take over the whole screen, possible buttons for each menu item

**Comment by postmastersteve** [comment]
+1 Danai Athanasoula ticket 146517

**Comment by danjonlam** [comment]
+1 Antony Merat ticket 146403

**Comment by bdvphoto** [comment]
Are we still going to see? :

Via @lalunecreative

#1- Hamburger icon customization (size, transparency, animation, colors, etc) 
#2- Ability to add things like logos/buttons/social icons 
#3 - Ability to remove/edit slideout shadow 
#4 - Ability to switch sides (show hamburger/slideout on left or right side of browser)

MrJPH commented on Jun 30
Making the whole Mobile Menu into an actual sidebar! That can be hidden away until opened, just as the Mobile Menu is now - except, be a sidebar! Able to be treated like any other sidebar with text, images, code, widgets, what have you! <---> Yes, please! :-D

I would love the option to place contact information and social icons in the mobile menu
