### ISSUE TITLE
Design import widget problems

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#359]
Opening this because a handful of designers have been reporting problems related to importing designs (especially into the ProPhoto design store).  Fatal errors, duplicated widgets, image widgets pointing to the wrong image, etc.

See https://prophoto6.zendesk.com/agent/tickets/1099
See https://prophoto6.zendesk.com/agent/tickets/1019

**Comment by brianium** [comment]
We discovered a problem with importing widgets related to syncing up ids with the appropriate column. The more templates in a design, the bigger the problem. Basically widget ids are getting mangled in a pretty extreme manner. The fix seems pretty straight forward so INCOMING!

**Comment by jaredh159** [comment]
Closing because I think https://github.com/netrivet/prophoto-issues/issues/364 fixes this.
