### ISSUE TITLE
Video backgrounds

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#363]
Sort of like gallery backgrounds, especially for vheight blocks.  For an example of what people are after, see:

http://amandahollowayphotography.com

**Comment by lalunecreative** [comment]
+1 P6 NEEDS video support. We're way behind in this area. Plus, all our competitors have it already.

**Comment by caryn-photog** [comment]
I agree - video is a must-have

**Comment by jaredh159** [comment]
+1 Tiffany Kelley

**Comment by creative-resort** [comment]
Using WordPress native functionality, this is already possible:
https://codex.wordpress.org/Video_Shortcode

**Comment by creative-resort** [comment]
Embedding videos from a CDN (vimeo, YouTube etc) is also possible using the text widget:
https://www.prophoto.com/beta/prophoto6/widgets/text-widget/

For vimeo embeds that work even in P5 (full width), I've developed a handler, that avoids the initial black screen and shows the intro frame image instead.

**Comment by modernistudios** [comment]
I like the idea of placing the tiles anywhere we want. what do you guys think?

**Comment by benjamintennant** [comment]
+1 Paul Mcmilllan ticket #139014

**Comment by postmastersteve** [comment]
+1 Cindy Boisvert ticket 143251

**Comment by postmastersteve** [comment]
+1 Alyssa Goslee ticket 144862

**Comment by postmastersteve** [comment]
+1 Alyssa Flaten ticket 145071

**Comment by modernistudios** [comment]
The thing is editing the blocks in P6 is not easy you must understand that each block has a specific size height that needs to be modified

**Comment by modernistudios** [comment]
There's also an overflow criteria that must be met on the blocks that you're editing for you to be able to see your video I completely got it now I understand exactly what needs to happen in order to have a video back on on your website

**Comment by lalunecreative** [comment]
The idea is to make the videos responsive and span browser widths, columns, etc. They'll make it work. The height options are coming eventually too so I'm sure those will tie into them in some way.

**Comment by modernistudios** [comment]
Lalunacreative how can I make mine responsive to width changes ? Www.modernisdios.com

**Comment by lalunecreative** [comment]
Until it's built in use - http://embedresponsively.com/

**Comment by benjamintennant** [comment]
+1 Rick Thompson ticket ticket 3976

**Comment by benjamintennant** [comment]
+1 Nikki Herdman ticket 147302 wants video options - particularly modals - but backgrounds too.

**Comment by postmastersteve** [comment]
+1 Sebastian Gonzalez ticket 147593

**Comment by benjamintennant** [comment]
+1 Christina Wehbe ticket 148019 - wants more video options, in general. Referenced the video gallery layout at http://stephenhamilton.com/ as an example.

**Comment by postmastersteve** [comment]
+1 Brad Lemon ticket 148585

**Comment by benjamintennant** [comment]
+1 Benjamin Sexson ticket 148980

**Comment by benjamintennant** [comment]
+1 Hector Añaños ticket 149316

**Comment by benjamintennant** [comment]
+1 Pierre Wolff ticket 150813

**Comment by postmastersteve** [comment]
+1 Michael Padilla ticket 150955

**Comment by benjamintennant** [comment]
+1 Barry Staver ticket 151577

**Comment by postmastersteve** [comment]
+1 Claudia Garcia ticket 152612

**Comment by benjamintennant** [comment]
+1 Carla Jacobson ticket 152848

**Comment by postmastersteve** [comment]
+1 Eryk Pajaczkowski ticket 154049

**Comment by postmastersteve** [comment]
+1 Syed Raza ticket 154065

**Comment by benjamintennant** [comment]
+1 Jerry Cantave ticket 154640

**Comment by postmastersteve** [comment]
+1 Lori Rutledge ticket 155258

**Comment by benjamintennant** [comment]
+1 Abo Jassin ticket 156058

**Comment by benjamintennant** [comment]
+1 Stephen Lamont ticket 156891

**Comment by postmastersteve** [comment]
+1 Jakub Vozenilek ticket 158597

**Comment by benjamintennant** [comment]
+1 Niki Bartelt ticket 159075

**Comment by swoone** [comment]
+1 Yes!!

**Comment by benjamintennant** [comment]
+1 Angela Mohney ticket 160026

**Comment by jaredh159** [comment]
Completed in `6.18.0`.
