### ISSUE TITLE
Allow hiding date and/or title for gallery permalink pages

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#365]

**Comment by northfolkco** [comment]
+1 Northfolk

On Tue, Feb 23, 2016 at 6:08 AM, Jared Henderson <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netrivet/prophoto-issues/issues/365>.
>



-- 

Sam & Rachel  //  Design & Branding
Website <http://www.northfolk.co/>  //  Shop <http://shopnorthfolk.co>  //
Facebook <https://www.facebook.com/northfolkco>  //  ProPhoto
<http://www.prophoto.com/designer/northfolk>

**Comment by lalunecreative** [comment]
+1

**Comment by postmastersteve** [comment]
+1 Mindy ticket 1825

**Comment by benjamintennant** [comment]
+1 from Richard Harris for hiding date on proofing galleries

**Comment by postmastersteve** [comment]
+1 Kathy Smith ticket 3192

**Comment by benjamintennant** [comment]
+1 Rebecca Davidson

**Comment by benjamintennant** [comment]
+1 Missy ticket 3306

**Comment by danjonlam** [comment]
+1 Jacquelyn Miller 143336

**Comment by postmastersteve** [comment]
+1 Theresa Valls ticket 143417
( her site is _amazeballs_ - her words )

**Comment by danjonlam** [comment]
+1 Jessica 3432

**Comment by danjonlam** [comment]
+1 Helen Ransom 3456

**Comment by danjonlam** [comment]
+1 Allison 3465

**Comment by benjamintennant** [comment]
+1 Ashley Jankowski

**Comment by danjonlam** [comment]
+1 Tom Forrest ticket 145213

**Comment by benjamintennant** [comment]
+1 Erin Cheatham ticket 3964

**Comment by danjonlam** [comment]
+1 Breanna Biliak ticket 145557

**Comment by danjonlam** [comment]
+1 Grace Laird ticket 145841

**Comment by benjamintennant** [comment]
+1 Andrea Husted ticket 146424

**Comment by jaredh159** [comment]
Closed by `6.14.0`
