### ISSUE TITLE
Image widget column spacing problems in IE11

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#366]
A layout that looks like this in chrome:

![2016-02-23_09-44-34](https://cloud.githubusercontent.com/assets/7050938/13255025/15b4ac7e-da12-11e5-93af-1ae715560463.png)

Looks like this in IE11:

![2016-02-23_09-43-43](https://cloud.githubusercontent.com/assets/7050938/13255032/1f80f58c-da12-11e5-8773-4ac80b52a1c4.png)

To replicate, use this design zip export:

https://files.slack.com/files-pri/T03HBM1GN-F0NKVB812/download/chris_cook.zip

**Comment by meatwad5675** [comment]
https://prophoto6.zendesk.com/agent/tickets/1105
