### ISSUE TITLE
Leverage featured images in layouts

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#371]
We could do a lot of cool things with featured images.  We could have blocks in templates that allow the background to be set to "featured image", which dynamically swaps it on on each page.  We could allow in image widgets a selection of "featured image", so it would change on each page.

**Comment by jonryder** [comment]
It would be great to be able to incorporate featured images into blog posts at full-width (e.g. as a page header) to give more impact.

**Comment by lalunecreative** [comment]
I was thinking the same thing. "Blog post widget" would be neato. You could have the ability to mess with the title placement, animation, full width etc.

**Comment by benjamintennant** [comment]
+1 Fritz wants to display the post/page featured image as the header. This would be maybe a "featured image" widget or something like that.

**Comment by benjamintennant** [comment]
+1 Trish Reda, ticket 2266

**Comment by TRTAFT** [comment]
I Love this idea and thank you for sharing.  Sometimes I write, sometimes I don't.  I like the idea of a main image.  Or something like excerpts where a background would roll out over or under the image with the text.

**Comment by postmastersteve** [comment]
+1 Giuseppe Voci ticket 141469

**Comment by postmastersteve** [comment]
+1 Roxana Snedeker ticket 3083

**Comment by postmastersteve** [comment]
+1 Steffen Harris ticket 142875

**Comment by benjamintennant** [comment]
+1 Martin ticket 3175

**Comment by JenniferClare** [comment]
Would love to have this facility on posts and pages (not sure if right thread for it though).
http://docs.flothemes.com/rebecca-posts-title-decoration/

**Comment by postmastersteve** [comment]
+1 Nicole Schiessl ticket 144307

**Comment by postmastersteve** [comment]
+1 Martin Olszewski ticket 145562

**Comment by benjamintennant** [comment]
+1 Patricio L. Sillero ticket 146191

**Comment by danjonlam** [comment]
+1 Amber Rostant ticket 147648

**Comment by danjonlam** [comment]
+1 Brea Robinson ticket 148140

**Comment by benjamintennant** [comment]
+1 Samantha Culp ticket 148303

**Comment by postmastersteve** [comment]
+1 Jarosław Tomaszewski ticket 148939

**Comment by danjonlam** [comment]
+1 Mauro Cavassana ticket 150198

**Comment by benjamintennant** [comment]
+1 Eddie Bojorquez ticket 150093 wants gallery pages to be able to have a title that sits over a featured image (maybe a background) above the gallery

**Comment by postmastersteve** [comment]
+1 Amanda Schoch ticket 150339

**Comment by benjamintennant** [comment]
+1 Cheng-Li Lin ticket 150736

**Comment by postmastersteve** [comment]
+1 Terri Lindholm ticket 150911

**Comment by postmastersteve** [comment]
+1 Jonathan Ryder ticket 151714

**Comment by danjonlam** [comment]
+1 Roxana Snedeker ticket 152119 - blog post featured image appears as cover/header image at the top of the individual post page

**Comment by benjamintennant** [comment]
+1 Daniel Toader ticket 152261 - wants a post or page title that's full width with background image and can be put in the template as a widget. The idea is to have it be dynamic so that you could create a single template for all pages and have the page title (and background, using the featured image?) display where you want.

**Comment by benjamintennant** [comment]
+1 Jennifer Hejna ticket 153344

**Comment by benjamintennant** [comment]
Wants a featured image to automatically display above or below the post title or perhaps as a background for the title

**Comment by benjamintennant** [comment]
+1 Page Teahan ticket 157618 - wants a full width header image for each post to be auto generated from the featured image

**Comment by danjonlam** [comment]
+1 Alex Bradbury ticket 158987 - featured image at the top of individual post pages

**Comment by postmastersteve** [comment]
+1 Afshin Jafari ticket 159120

**Comment by danjonlam** [comment]
+1 Adrian Cotiga ticket 160160

**Comment by postmastersteve** [comment]
+1 Christina Ruoff ticket 161861
feature image widget or background image

**Comment by benjamintennant** [comment]
+1 Luke Chisholm ticket 161876 - wants to leverage featured images behind titles on top of posts as the header.

**Comment by jaredh159** [comment]
Completed in `6.19.0`.
