### ISSUE TITLE
beta37 Menu and logo malfunction on IE

### ISSUE THREAD

**Issue by dtsiapas** [netrivet/prophoto-issues#381]
Everything works fine on Opera, Chrome and Firefox
http://www.tsiapas.com/blog/

But there seems to be an issue with Internet explorer (Microsoft Edge 25.10586) where either the menu is not working at all
http://www.tsiapas.com/blog/

or it is malfunctioning 
http://www.tsiapas.com/blog/non-portrait-iii-one-image/

**Comment by brianium** [comment]
@dtsiapas I just loaded the pages you linked in IE10, IE11, and Edge and it looked like everything was working fine. Maybe I am missing something. Can you clarify what is not working?

**Comment by dtsiapas** [comment]
The problem is with Microsoft Edge (I tested the on site on Internet Explorer and it is fine)
The menu and the logo are not loading on Edge and i replicated the issue on four pcs running windows 10.

**Comment by brianium** [comment]
@dtsiapas Do these screenshots look correct? I took them on a Windows 10 box running Edge. Just want to make sure we are talking about the same thing :)

![screen shot 2016-03-01 at 12 59 37 pm](https://cloud.githubusercontent.com/assets/636651/13436541/bce2fce4-dfad-11e5-939a-8738be788c00.png)

![screen shot 2016-03-01 at 1 00 45 pm](https://cloud.githubusercontent.com/assets/636651/13436550/c6089964-dfad-11e5-9ca1-dad6f1401b6d.png)

**Comment by dtsiapas** [comment]
@brianium  The site renders correctly on your screenshots!

I am sending you what i experience here on my pcs

![screenshot edge](https://cloud.githubusercontent.com/assets/16962947/13436671/20061082-dfe9-11e5-8bc3-5ebf92292cf1.jpg)
![screenshot edge](https://cloud.githubusercontent.com/assets/16962947/13436745/5df1cd8c-dfe9-11e5-8b54-f2ed736f2ef8.jpg)

**Comment by brianium** [comment]
Well that is strange.... are you logged in while you view this? If so can you log out and see if you are seeing the same thing as me?

**Comment by dtsiapas** [comment]
Either I am logged in or not i experience the same thing

**Comment by brianium** [comment]
I am going to try and upgrade my edge version. I am currently on version `20.10240.16384.0`

**Comment by brianium** [comment]
@dtsiapas I am using the virtual machines provided my microsoft for testing edge, and unfortunately they keep the OS version pinned down, so I cannot update my Edge version. This seems like a bug in the latest version of Edge, but it may take some time for me to get an up to date version of Edge running for me to test. I will leave this thread open in the meantime and update you as soon as I have more information. Thanks!

**Comment by dtsiapas** [comment]
@brianium Ok Brian, we will see how it goes. Thank you!

**Comment by brianium** [comment]
I sent a tweet at the Edge team about getting an up to date VM for testing, and they said they are working on it :) - We will get this fixed one way or another.

**Comment by brianium** [comment]
@dtsiapas do you know if this is still a problem? The Microsoft Edge team seems to be in no hurry to update their virtual machines. If this is still a problem we might have to setup a windows machine to do some testing.

**Comment by dtsiapas** [comment]
As you can see the problem with MS Edge is still persistent in
      beta 56
    
    
    
    
    
    On 6/5/2016 7:06 PM, Brian Scaturro
      wrote:
    
    
      @dtsiapas do you know if this is
        still a problem? The Microsoft Edge team seems to be in no hurry
        to update their virtual machines. If this is still a problem we
        might have to setup a windows machine to do some testing.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly or view
          it on GitHub
      
        
          
          
        
        
      
    
    
  

	
        
		Virus-free. www.avast.com

**Comment by brianium** [comment]
Hmmm. Was there an image you intended to attach to the response? It is not showing up on GitHub.

I just pulled down the latest VM, and I am seeing this issue on http://www.tsiapas.com/blog/non-portrait-iii-one-image/:

![screen shot 2016-05-06 at 1 32 52 pm](https://cloud.githubusercontent.com/assets/636651/15081106/1f715e7c-138f-11e6-9e22-5784faa7b853.png)

Does this capture the problem? Or am I missing some larger problems?

**Comment by dtsiapas** [comment]
Yes i tried to send an
      image. Sorry it was a printscreen and perhaps it was bitmap, now i
      am sending it as jpg.
      
      The problem on my system is a bit worse because the menu overlaps
      with the logo. 
      I can replicate the same problem on three pcs with windows 10 x64
      
      
      
      
      
    
    On 6/5/2016 8:34 PM, Brian Scaturro
      wrote:
    
    
      Hmmm. Was there an image you intended to attach to the
        response? It is not showing up on GitHub.
      I just pulled down the latest VM, and I am seeing this issue on
        http://www.tsiapas.com/blog/non-portrait-iii-one-image/:
      
      Does this capture the problem? Or am I missing some larger
        problems?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly or view
          it on GitHub
      
        
          
          
        
        
      
    
    
  

	
        
		Virus-free. www.avast.com

**Comment by brianium** [comment]
@dtsiapas bah! sorry - it looks like Github is not displaying images from email responses. When you get a moment, would you mind adding the image on GitHub itself?

**Comment by dtsiapas** [comment]
![clipboard image](https://cloud.githubusercontent.com/assets/16962947/15082152/e72b1342-13ce-11e6-87eb-615630bc4380.jpg)

**Comment by brianium** [comment]
@dtsiapas just wanted to let you know that we are investigating. Newer versions of Edge seem to interpret some key CSS in a very different manner than every other browser. It seems like a pretty big misstep on Edge's part (in case specifics are interesting to you, it has to do with the CSS property `box-sizing` and `border-box`).

We are going to investigate a solution that will not impact every other browser. Thank you for your patience on this.

**Comment by dtsiapas** [comment]
Thank you Brian for the update!
    
    Hopefully very few use Edge for browsing
    
    
    
    On 5/11/2016 6:29 PM, Brian Scaturro
      wrote:
    
    
      @dtsiapas just wanted to let you know
        that we are investigating. Newer versions of Edge seem to
        interpret some key CSS in a very different manner than every
        other browser. It seems like a pretty big misstep on Edge's part
        (in case specifics are interesting to you, it has to do with the
        CSS property box-sizing and border-box).
      We are going to investigate a solution that will not impact
        every other browser. Thank you for your patience on this.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly or view
          it on GitHub
      
        
          
          
        
        
      
    
    
  



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com

**Comment by jaredh159** [comment]
We haven't had any other customers report this issue, so closing for now.
