### ISSUE TITLE
Word-wrap: break-word doing weird things on iPad

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#387]
![2016-03-02_15-02-25](https://cloud.githubusercontent.com/assets/7050938/13473584/f71b9580-e087-11e5-95f1-b94eb510789d.png)

**Comment by northfolkco** [comment]
getting the same thing over here.

**Comment by jaredh159** [comment]
This will be fixed in the build coming out tomorrow morning
