### ISSUE TITLE
Allow max-height constraint for content images

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#395]
In P5, you could set a max-height, so that you could still upload large, retina-ready content images of portrait orientation, and make sure they didn't display huge.

We need a similar concept in P6. With portrait-aspect images uploaded very large, it's easy to get undesirable results where the images are too large and you have to scroll to see them.

**Comment by TimKamppinen** [comment]
This might be impossible but it would be great if there was an option to enable this on a per-image basis... for instance, I might have a single vertical image that I want to be seen in it's entirety on a horizontal screen.  However, in the same blog post I might have a vertical collage of photos that I want to fill the width of the content area, since each individual image (in the single .jpg layout) is small enough to fit in the viewport.

**Comment by lalunecreative** [comment]
+1

**Comment by JenniferClare** [comment]
+1

**Comment by benjamintennant** [comment]
+1 David Bock in #1890

**Comment by benjamintennant** [comment]
+1 Beckie #1993 - wants a max height constraint for galleries

**Comment by postmastersteve** [comment]
+1 Thomas Geist ticket 2136

**Comment by danjonlam** [comment]
+1 Sarah Jones ticket 140462

**Comment by benjamintennant** [comment]
+ Fritz #2305 wants max height restriction for galleries (he would actually like width restraints as well)

**Comment by benjamintennant** [comment]
+1 Sarah ticket 2048 - wants max-height option for gallery images

**Comment by benjamintennant** [comment]
+1 Katrina Barrow - wants to be able to restrict gallery size 2439

**Comment by postmastersteve** [comment]
+1 Dina Duchan ticket 140705

**Comment by postmastersteve** [comment]
+1 Kylie Mitchell ticket 140403

**Comment by postmastersteve** [comment]
+1 Missy ticket 2619

**Comment by postmastersteve** [comment]
+1 Gary Chen ticket 141147

**Comment by postmastersteve** [comment]
+1 Carlos Meraz ticket 141292

**Comment by postmastersteve** [comment]
+1 Ely Roberts ticket 141457

**Comment by postmastersteve** [comment]
+1 Wendy Wang ticket 141458

**Comment by postmastersteve** [comment]
+1 Loic Nicolas ticket 2756

**Comment by postmastersteve** [comment]
+1 Mallory Haren ticket 141596

**Comment by danjonlam** [comment]
+1 Scott Reeves 142345

**Comment by danjonlam** [comment]
+1 Steve Bennett 142581

**Comment by postmastersteve** [comment]
+1 Michelle ticket 3145

**Comment by postmastersteve** [comment]
+1 Jennifer Clare ticket 3190

**Comment by postmastersteve** [comment]
+1 Theresa Valls ticket 143417

**Comment by danjonlam** [comment]
+1 Jacki Miller 143336 - image width too
