### ISSUE TITLE
Can't add WordPress comments if Facebook comments also enabled

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#396]
> When I enable facebook comments (with traditional comments still enabled) the comment entry box for traditional comments disappears, although it still says "No Comments" below the facebook comments.

Steve and Benjamin both confirmed

**Comment by lalunecreative** [comment]
This one is now closed - https://github.com/netrivet/prophoto-issues/issues/494 so I guess that means this one should be too.

**Comment by jaredh159** [comment]
@lalunecreative yeah, thanks.
