### ISSUE TITLE
Add ability to duplicate template

### ISSUE THREAD

**Issue by caryn-photog** [netrivet/prophoto-issues#403]
When designing, it's easier to start with the simplest and build on/change that.  Would be great to be able to duplicate the template in the Template Manager instead of having to redo from scratch.

**Comment by jaredh159** [comment]
Thanks for your feedback!  We have an open ticket for this:

https://github.com/netrivet/prophoto-issues/issues/269

And, even though the roadmap says it's not coming for a few months, I can give you some inside information that we fast-tracked it, and the feature is already essentially done, and will be released in less than a week!

**Comment by caryn-photog** [comment]
Thank you - sorry about the dupe issue. Did a search and didn't come up with everything so I obviously still need to get used to the system.  Super excited for the update. Have been having fun playing today!
