### ISSUE TITLE
Image lazyloading

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#410]

**Comment by jaredh159** [comment]
+1 Rich Smith

**Comment by lalunecreative** [comment]
+1 would cut down load times, I'm all for this.

**Comment by photog0411** [comment]
Can you add lazyloading for slideshow galleries? And an option to only lazyload the first couple images while the rest load in background after slideshow starts (kind of how a youtube video buffers)

**Comment by danjonlam** [comment]
+1 Sebastian Buff 143735

**Comment by jaredh159** [comment]
Completed in `6.8.0`
