### ISSUE TITLE
Vertical menu spacing top/bottom not applying

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#414]
![2016-03-14_11-34-43](https://cloud.githubusercontent.com/assets/7050938/13757603/ab6fb710-e9fb-11e5-91a4-c2f3e773047a.png)

**Comment by lalunecreative** [comment]
That's funny. This one didn't start showing up until AFTER #44.

You can tell since it's on Redwood's home page. The 3 menu items in the pricing table. - https://www.prophoto.com/store/redwood-6/

**Comment by brianium** [comment]
@lalunecreative are you saying something is still off with this? Or does it look right now? It looks like we were just straight up not applying this customization until 44.

**Comment by lalunecreative** [comment]
Actually it was always applying fine in ours until 44. Those menus are
huge. When I try to change the setting nothing happens.

On Friday, March 18, 2016, Brian Scaturro <notifications@github.com> wrote:

> @lalunecreative <https://github.com/lalunecreative> are you saying
> something is still off with this? Or does it look right now? It looks like
> we were just straight up not applying this customization until 44.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/netrivet/prophoto-issues/issues/414#issuecomment-198328997>
>


-- 
www.lalunecreative.com

**Comment by lalunecreative** [comment]
Ok well nevermind. I had a video going showing how it was all jacked up
which it was. I went into the individual column settings for vertical menus
and then just peeked around, went to make a new video and went back into
the menu settings and all of a sudden it started working correctly and it
started showing the right spacing on both the back and the front end. It
hadn't been doing that before. So I guess it works fine now. I hate these
ghost bugs that I get proof of, they fix themselves then I can't reproduce
it any more. Annoying as all get out.

Matt-

www.lalunecreative.com

**Comment by brianium** [comment]
Yeah man. Computers are hard :computer: - glad its work now!
