### ISSUE TITLE
Bad error feedback when uploading too large design zip

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#416]
If you upload a design zip that exceeds your `upload_max_filesize`, you get a pretty bad error message:

![2016-03-16_09-09-41](https://cloud.githubusercontent.com/assets/7050938/13813284/1bf51424-eb57-11e5-8ef9-e1703c41dd5b.png)

![2016-03-16_09-09-55](https://cloud.githubusercontent.com/assets/7050938/13813287/1fe7aea2-eb57-11e5-891e-c791e18c4c63.png)

Also, if you upload the outer zip file instead of the inner, it not only doesn't work, but it silently fails with no error message.

**Comment by creative-resort** [comment]
**Observation:**
On some servers, the response headers in this case are simply of type Error "500", with no error message or further response details.
In this case, the error message displayed by ProPhoto is still the same as above, empty.

**Proposal:**
Showing a message 
> Internal Server Error 500

maybe as a title, could be helpful.
