### ISSUE TITLE
Cropped grid not keeping even rows with excerpt text

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#421]
Because of how P6 handles responsive grids, all grids (cropped and masonry) are laid out by javascript.  Currently we just rely on the fact that uniform cropped images produce even rows, but this doesn't hold up when you've got excerpt text of various lengths, as shown below.  Something needs to be done to ensure even rows when the style is cropped.

![2016-03-17_10-55-59](https://cloud.githubusercontent.com/assets/7050938/13850179/4b6376c8-ec2f-11e5-9104-f164dfded898.png)

**Comment by benjamintennant** [comment]
+1 Elon Reynolds #1633, he's wanting a way to choose the length of the excerpt text both for text below and rollover galleries for a more uniform visual appearance.

**Comment by benjamintennant** [comment]
Sven ticket 2399

**Comment by benjamintennant** [comment]
+1 Yvette johnson ticket 2702

**Comment by danjonlam** [comment]
+1 Jacki Miller - 143336

**Comment by postmastersteve** [comment]
+1 Tina ticket 3679

**Comment by benjamintennant** [comment]
+1 Wisam Mahmood ticket 145063

**Comment by brianclaryphoto** [comment]
+1

**Comment by danjonlam** [comment]
+1 Hugh #145479

**Comment by danjonlam** [comment]
+1 Yen Ke ticket 145464

**Comment by danjonlam** [comment]
+1 Lisa Drew ticket 145282

**Comment by postmastersteve** [comment]
+1 Jared Knetzer ticket 145861

**Comment by jaredh159** [comment]
Completed in `6.10.0`
