### ISSUE TITLE
Customizer fatal error on early builds of PHP 5.3

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#424]
`DOMDocument::saveHTML()` did not take a parameter until `5.3.6`, see:

http://www.php.net/manual/en/domdocument.savehtml.php

and

`ProPhoto\Infrastructure\Transform\Widget\FormMarkupTransform:35`

This causes a fatal error.  Now, nobody should be running < `5.3.6`, but we need to figure out what to do here.  Either find a way to do this in a way that works for all 5.3+, or we need to make a hard distinction that we don't support < `5.3.6`.

**Comment by brianium** [comment]
We will probably up our minimum version to 5.3.6 or 5.4 pending gathered stats.
