### ISSUE TITLE
Settings modal tutorials showing repeat content

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#425]
Steps to replicate:

1. On a non-local site (like staging), go to "ProPhoto" > "Settings" > "Copyright"
2. Click on the life-saver icon for "Footer attribution links removal"

Tutorial is repeated 3 times.

**Comment by meatwad5675** [comment]
Fixed this via a change on our support site to give ProPhoto6 modal tutorial views the correct content
