### ISSUE TITLE
Add opacity to all color sliders

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#430]

**Comment by jaredh159** [comment]
+1 Tiffany Kelley

**Comment by lalunecreative** [comment]
+1

**Comment by lalunecreative** [comment]
This is pretty much the same thing #415

**Comment by benjamintennant** [comment]
+1 Mike McEwen ticket 3592

**Comment by benjamintennant** [comment]
+1 Bruce from bdv.photography ticket 3890 

> It would be nice to be able to change the opacity of backgrounds.

**Comment by postmastersteve** [comment]
+1 Nely Ariza ticket 145965

**Comment by jaredh159** [comment]
Completed in `6.10.0`
