### ISSUE TITLE
Gallery image management enhancements

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#436]
In general, the tools we offer for managing images in a gallery are pretty basic.  It's difficult to work with a large number of images to reorder or delete things because we currently can only re-order manually one image at a time, and same with deleting.

* reorder all images by filename, date, etc (like proofing)
* delete multiple images at once

**Comment by jaredh159** [comment]
+1 David 2027

**Comment by brianium** [comment]
Removed multi drag from this enhancement so we could clear out the enhancements that are shipping. Created a separate issue specifically for multi drag here:

https://github.com/netrivet/prophoto-issues/issues/543
