### ISSUE TITLE
Use image from embedded gallery as fallback post excerpt image

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#438]
If you have a grid of recent posts, and a recent post has only a gallery embedded, no other images or featured image, the grid will not load an image.  It should, in this case, use the first image from the gallery as the excerpt image.

**Comment by postmastersteve** [comment]
+1 Wendy Wang ticket 141647

**Comment by postmastersteve** [comment]
+1 James Breadmore ticket 144270

**Comment by jaredh159** [comment]
Completed in `6.10.0`
