### ISSUE TITLE
More template assignment options

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#439]
Including:

* blog categories
* custom post types
* individual galleries
* proofing galleries

And maybe even...

* custom post type taxonomies (categories)
* individual posts (only supports individual pages currently)

**Comment by northfolkco** [comment]
+ 1 Northfolk!

**Comment by lalunecreative** [comment]
+1

**Comment by lalunecreative** [comment]
Combine with this ticket - https://github.com/netrivet/prophoto-issues/issues/427 which is an option to add a template to the 404 page. I would definitely start designing pages for this if we had this option.

**Comment by postmastersteve** [comment]
Proofing has no template assignment options yet, either - it borrows from the _posts page_ type. We may need:

- Proofing all galleries pages
- Proofing category pages
- Proofing parent gallery pages
...etc.

**Comment by bdvphoto** [comment]
+1 for the 404 page

**Comment by jaredh159** [comment]
+1 Brian Clary for _Proofing galleries_

**Comment by jaredh159** [comment]
+1 Courtney Keim for specifying templates for specific archive pages.  So for instance, the archive of all blog posts in the category "wedding" could also be assigned a template.

**Comment by danjonlam** [comment]
+1 Sean Wytrwal 140775

**Comment by danjonlam** [comment]
+1 Jamie ticket 2740

**Comment by danjonlam** [comment]
+1 Amanda Nordhagen 140901

**Comment by jaredh159** [comment]
+1 Sven for _Proofing Galleries_

**Comment by postmastersteve** [comment]
+1 Andrew Hackett ticket 141896 for _Proofing Galleries_

**Comment by danjonlam** [comment]
+1 Nicholas Bombich 142213

**Comment by jaredh159** [comment]
Released in 6.3.0.
