### ISSUE TITLE
Customizable search & form elements

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#447]
Search input field needs lots of customization options.  It probably might mesh well with work that needs to be done for the contact form, which heavily features html form inputs.  We could allow design or template-level styling of form inputs that would apply to search inputs, contact form inputs, and elsewhere.

**Comment by lalunecreative** [comment]
+1

**Comment by reneebell** [comment]
yes please!

**Comment by courtina** [comment]
yes yes yes!

**Comment by benjamintennant** [comment]
+1 Lisa #2111 wants a dropdown search input area as an option in search menu item

**Comment by danjonlam** [comment]
+1 Juliana Redondo 140951 - dropdown form option (e.g. What are you looking for? dropdown - Wedding, Newborn, etc)

**Comment by danjonlam** [comment]
+1 Shellie Burkhalter 141007 - contact form dropdown form field

**Comment by postmastersteve** [comment]
+1 Kaley Diaz ticket 2913

**Comment by benjamintennant** [comment]
+1 Aysegul Sanford ticket 142496 - wants customizable search form like we had in p5

**Comment by postmastersteve** [comment]
+1 Abbeygail Elaine ticket 3098
wants custom search menu item appearance

**Comment by danjonlam** [comment]
+1 Krissy Miller 142696 Customization of search field

**Comment by benjamintennant** [comment]
+1 Meghann ticket 3891 wants customizable search widget

**Comment by postmastersteve** [comment]
+1 Jackson Eddy ticket 145057
the menu should provide a customizable search icon with dropdown search box

**Comment by postmastersteve** [comment]
+1 Kelly Barr ticket 145115
search widget appearance

**Comment by postmastersteve** [comment]
+1 Kristin Pruis ticket 145919
form appearance

**Comment by benjamintennant** [comment]
+1 Gerry Sulp ticket 146544

**Comment by lalunecreative** [comment]
Allow tile or image upload for submit button

**Comment by danjonlam** [comment]
+1 Linda Ramdane ticket 147483

**Comment by postmastersteve** [comment]
+1 Danielle Parker ticket 147801
not just search & form, but also the dropdowns created by WordPress widgets, e.g. _Categories_ and _Archives_ widgets which are set to appear as a dropdown box:

![2016-09-28_11-55-50](https://cloud.githubusercontent.com/assets/275742/18921391/92e95616-8572-11e6-95f2-5fb398cffaf6.png)

**Comment by danjonlam** [comment]
+1 Rachel Luna ticket 150710

**Comment by reneebell** [comment]
is there any update on this?
eta?

**Comment by postmastersteve** [comment]
+1 Michael Padilla ticket 151459

**Comment by postmastersteve** [comment]
@jaredh159 or @brianium could we label this with **Forms** it took me a little extra time to find this one...

**Comment by benjamintennant** [comment]
+1 Lisa-Marie Chandler ticket 153134

**Comment by postmastersteve** [comment]
+1 Megan Marlene Peter ticket 155761

**Comment by benjamintennant** [comment]
+1 Heather Cook ticket 155759 - requesting to customize the WordPress search widget

**Comment by danjonlam** [comment]
+1 Vail Fucci ticket 156853

**Comment by danjonlam** [comment]
+1 Leigh Roth ticket 157329 - checkbox form fields

**Comment by danjonlam** [comment]
+1 Dina Duchan ticket 156419 - checkbox/multiple choice form fields

**Comment by postmastersteve** [comment]
+1 Timothy Thomas ticket 157773
contact form styling

**Comment by postmastersteve** [comment]
+1 Amanda Rae Montgomery ticket 157680
search field/button styling

**Comment by benjamintennant** [comment]
+1 Heather Espana ticket 158179 - wants a dropdown search option for menus like in p5

**Comment by postmastersteve** [comment]
+1 Piotr Dziwak ticket 158248

**Comment by benjamintennant** [comment]
+1 Amy Pederson ticket 158376 - wants to customize search widget or menu item

**Comment by benjamintennant** [comment]
+1 Charlotte Razzell ticket 157231 - options for styling form fields

**Comment by danjonlam** [comment]
+1 Melissa Hersey ticket 158553

**Comment by benjamintennant** [comment]
+1 Charlotte Razzell ticket 157231 - customize search button

**Comment by benjamintennant** [comment]
+1 Lisa Rogers ticket 158702 - more spacing options for between labels and input fields in forms.

**Comment by benjamintennant** [comment]
+1 Susan Tuttle ticket 158427 - more style options for form field area (labels, inputs, textarea)

**Comment by postmastersteve** [comment]
+1 Josée Lamarre ticket 159200
style controls for the P6 forms (labels, entry text)

**Comment by postmastersteve** [comment]
+1 Carrie ticket 159642
style control for field labels and for field text

**Comment by benjamintennant** [comment]
+1 Anna Hawk ticket 160008 - wants to style the appearance of her form

**Comment by susantuttlephotography** [comment]
+1 Susan Tuttle ticket 158427 - scrolling speed options for parallax... In addition to the fixed background option for parallax, it would be cool if the background could scroll at a slower pace than the other elements. Like in this demo: http://keithclark.co.uk/articles/pure-css-parallax-websites/demo3/

**Comment by danjonlam** [comment]
+1 Valentin Turean ticket 160513 - style appearance of form fields

**Comment by lalunecreative** [comment]
+1 Todd Wilson

"What I had and wanted again was a regular “search” text in the menu like all my other menu items, but when you click on or hover over then it gives you that text bar" so basically the same menu search options we had in P5.

**Comment by benjamintennant** [comment]
+1 Shari Fleming ticket 161375 - wants a dropdown search menu item. Does not want the input field visible until you hover "search."

**Comment by postmastersteve** [comment]
+1 Samantha Culp ticket 162077
change box to underline, change field font style, change field background & border color, etc.

**Comment by benjamintennant** [comment]
+1 Aysegul Sanford ticket 162465 - wants to customize the search option

**Comment by danjonlam** [comment]
+1 Kueste Kreativ Tania und Chris Manteufel ticket 162867 - customizable search option

**Comment by jaredh159** [comment]
Completed in `6.19.0`.
