### ISSUE TITLE
Image Captions in Galleries

### ISSUE THREAD

**Issue by ThomasGeist** [netrivet/prophoto-issues#449]
I haven't found anything about this so I am posting it here. If it's already posted, please point me to it.

Since PP addresses photographers, image captions are pretty important for many.
Any gallery (Including full screen and tile/grid galleries) should offer the display of captions.

Captions should be possible by either manually entering them or by pulling them from metadata.

I could imagine that there are also some photographers who wish to display EXIF fields as captions.

**Comment by lalunecreative** [comment]
Duplicate of this ticket - https://github.com/netrivet/prophoto-issues/issues/243

**Comment by jaredh159** [comment]
Closing, duplicate.
