### ISSUE TITLE
Gallery style in a carousel strip showing images side-by-side

### ISSUE THREAD

**Issue by postmastersteve** [netrivet/prophoto-issues#453]
A photo view which has a fixed aspect ratio, and images that have varied aspect ratios simply appear next to their neighbors. Navigation slides left/right. The _active_ image always appears dead-center in the view.
Example:  http://www.bryantandheather.com/love#4

**Comment by postmastersteve** [comment]
+1 Natalie Wilkinson  https://help.prophotoblogs.com/tickets/138377

**Comment by postmastersteve** [comment]
+1 Camryn Clair  https://help.prophotoblogs.com/tickets/138331

**Comment by ThomasGeist** [comment]
+1

**Comment by lalunecreative** [comment]
+1

**Comment by lalunecreative** [comment]
Also that gallery works with the magic mouse to use fingers to navigate so +2.

**Comment by postmastersteve** [comment]
+1 Russell Neal  ticket #1704

**Comment by JenniferClare** [comment]
+100 ;)
With the ability to restrict the height so it behaves like this: http://demo.flothemes.com/lovely-v1/

**Comment by brianclaryphoto** [comment]
+1 Have been wanting this for a long time :)

**Comment by danjonlam** [comment]
+1 Kristen Turechek ticket 2394

**Comment by camrynclairphoto** [comment]
+1 I have been debating buying flothemes bc they offer this feature BUT I really want to stay with Prophoto so lets make it happen!!!!!!!

**Comment by bdvphoto** [comment]
+1 we really need more options for displaying galleries. After all, Pro Photo is for photography sites so this should be a priority. .

**Comment by brianium** [comment]
@camrynclairphoto it is definitely on the list :) - This feedback matters a lot to us, and the more upvotes we get on an issue the sooner we are likely to get to it. Don't leave us yet! You are going to see all kinds of cool things coming.

**Comment by lyndacp** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Matt Ehnes ticket 141840 - wants what he sees at http://www.bryantandheather.com/love#5

**Comment by postmastersteve** [comment]
+1 Theresa Stanton ticket 3025

**Comment by danjonlam** [comment]
+1 Claire Brennan ticket 145513

**Comment by danjonlam** [comment]
+1 Andrea Couch Wofford ticket 147794

**Comment by danjonlam** [comment]
+1 Christian Ingram ticket 148049

**Comment by benjamintennant** [comment]
+1 Brendan Ottley from Facebook support group.
https://www.facebook.com/photo.php?fbid=10211624299273241&set=pcb.1246937668714504&type=3

**Comment by danjonlam** [comment]
+1 Katrina Johns ticket 150574

**Comment by danjonlam** [comment]
+1 Zara Clarke ticket 150582

**Comment by benjamintennant** [comment]
+1 Beckie Forseth ticket 150627

**Comment by postmastersteve** [comment]
+1 Alyssa Faoro ticket 151490

**Comment by benjamintennant** [comment]
+1 Heather Cook ticket 153152

**Comment by lalunecreative** [comment]
+Camryn Shonka via Facebook ProPhoto Support Group.

These are examples of what i want, friends sites that are made with square space and flo themes......
https://www.amandavanvels.com
http://nicoleclareyphoto.com

**Comment by postmastersteve** [comment]
+1 Rachel Thatcher

**Comment by benjamintennant** [comment]
+1 Beckie ticket 156134

**Comment by benjamintennant** [comment]
+1 Jasmine Pulley ticket 154213

**Comment by benjamintennant** [comment]
+1 Majesta Campbell ticket 156916

**Comment by bdvphoto** [comment]
Any update on this?

**Comment by danjonlam** [comment]
+1 Inge Kooiman ticket 158463

**Comment by benjamintennant** [comment]
+1 Katrina Barrow ticket 158582

**Comment by rtb1982** [comment]
Is there any update on this? Its one of the items i'm waiting on before purchasing the theme.

**Comment by brianium** [comment]
@rtb1982 we just wrapped up a round of general performance improvements and the [gallery height](https://github.com/netrivet/prophoto-issues/issues/627) feature. We are shipping this out at the end of this week or on Monday in the 6.16.0 release.

In general we try to prioritize based on the number of comments (i.e +1 votes) and general complexity of the task. 

This feature is creeping up to the top of the list after we ship 6.16.0. I'll update the ticket once I know more :)

**Comment by creative-resort** [comment]
+1

**Comment by danjonlam** [comment]
+1 Michelle Ladlow ticket 159018

**Comment by danjonlam** [comment]
+1 Giselle ticket 159513

**Comment by rtb1982** [comment]
I noticed that this was removed from the Sebastian roadmap?  Is it still on the radar?

**Comment by JenniferClare** [comment]
Wondering the same as @rtb1982  Carousel galleries are something I've been wanting for an age and nearly switched to Flothemes, so was really happy to see them on Sebastian...  :'(

**Comment by brianclaryphoto** [comment]
Same here!

**Comment by brianium** [comment]
@JenniferClare @brianclaryphoto @rtb1982 yes! The feature is actually complete. It will be released in 6.18. Just tying up some other features that are going into 6.18 as well. We are shooting for next week :)

**Comment by jaredh159** [comment]
Completed in `6.18.0`.

**Comment by camrynclairphoto** [comment]
So excited that the Carousel Gallery has been added..... NOW how do i create a Carousel Gallery? cant find it anywhere. thank you

**Comment by postmastersteve** [comment]
@camrynclairphoto this is a thread for ProPhoto feature requests.
If you need tech support, we're always glad to help, but please direct your messages through our website:
https://pro.photo/contact
Thanks!
