### ISSUE TITLE
Tile text layer alignment options

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#459]

**Comment by theresavs** [comment]
This would be nice because there is no center alignment and it would be nice to override the widget text alignment setting.

**Comment by lalunecreative** [comment]
Individual alignment options per widget is coming at some point, it's in a ticket somewhere, (or at least Jared as said it's coming) but I agree.

**Comment by meatwad5675** [comment]
+1 Rachel Thatcher

**Comment by jaredh159** [comment]
Released in 6.3.0.
