### ISSUE TITLE
Allow collapsing of blocks in customizer

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#463]
For **easier re-ordering** this is pretty important.  It would also help users to focus on the block they are working on.

+1 Cheryl Ford

**Comment by bdvphoto** [comment]
+1

**Comment by lalunecreative** [comment]
+1

**Comment by creative-resort** [comment]
+1
I had to add this via browser add-on, but would sure be easier if available out of the box

**Comment by lalunecreative** [comment]
Duplicate of this ticket - https://github.com/netrivet/prophoto-issues/issues/393

**Comment by danjonlam** [comment]
+1 Megan ticket #150695

**Comment by postmastersteve** [comment]
+1 Piotr Dziwak ticket 157277

**Comment by lalunecreative** [comment]
This one needs closed.

**Comment by jaredh159** [comment]
Oops, thanks @lalunecreative, closing
