### ISSUE TITLE
Copy/paste blocks, rows, and columns in customizer

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#474]
How to handle widgets within the source entity is a question we'd have to figure out.  We could duplicate those, or omit them.  Probably referencing the same widget instance again is a no go.

**Comment by melissalove** [comment]
Yes please :)

**Comment by lalunecreative** [comment]
+1

**Comment by theresavs** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Amanda 2391

**Comment by danjonlam** [comment]
+1 Kimberly 2431

**Comment by danjonlam** [comment]
+1 Erin 2796

**Comment by danjonlam** [comment]
+1 Hannah 3005

**Comment by benjamintennant** [comment]
+1 Martin 3174 (inheritance would be something to figure out here, as well)

**Comment by northfolkco** [comment]
+1 to duplicate without inheriting.

**Comment by lalunecreative** [comment]
+1 Duplicate without inheriting

**Comment by brianium** [comment]
@lalunecreative @northfolkco - you mean specifically with regards to customizations? or you wouldn't expect the copy to end up in child templates? both?

**Comment by northfolkco** [comment]
I really like how you can copy a widget and place it in other templates. So copy all block/row/column settings and widgets but place without inheriting from the original copied item.

**Comment by lalunecreative** [comment]
Exactly! It would save a bunch of time, because most of the time you're just looking for the same genearl settings without having to start from scratch.

**Comment by brianium** [comment]
@northfolkco perfect - that is exactly how we are approaching it. *whew*

**Comment by benjamintennant** [comment]
+ Alan Hutchison ticket 3338

**Comment by benjamintennant** [comment]
+1 Cheryl ticket 3444

**Comment by benjamintennant** [comment]
+1 Chris ticket  3567

**Comment by benjamintennant** [comment]
+1 Wisam Mahmood ticket 144043

**Comment by danjonlam** [comment]
+1 Mallory Davis ticket 143882

**Comment by danjonlam** [comment]
+1 Jacob 3618

**Comment by benjamintennant** [comment]
+1 Inge Kooiman ticket 144715

**Comment by danjonlam** [comment]
+1 Stacy Jacob 3962

**Comment by danjonlam** [comment]
+1 Judy Whitmore ticket 145840

**Comment by postmastersteve** [comment]
+1 Nely Ariza ticket 145965

**Comment by danjonlam** [comment]
+1 Laura Kent ticket 146265

**Comment by TRTAFT** [comment]
yes please

**Comment by postmastersteve** [comment]
+1 Joni Bilderback ticket 147680

**Comment by benjamintennant** [comment]
+1 Jessica Schilling ticket 149695

**Comment by benjamintennant** [comment]
+1 Mary Sylvia ticket 149856

**Comment by danjonlam** [comment]
+1 Rob Hooper ticket 150069

**Comment by benjamintennant** [comment]
+1 Anginet Page ticket 151434

**Comment by benjamintennant** [comment]
+1 Kati Mallory ticket 152136

**Comment by benjamintennant** [comment]
+1 Sonja Rakicevic ticket 152698

**Comment by benjamintennant** [comment]
+1 Tim Kamppinen ticket 154210

**Comment by TimKamppinen** [comment]
I think a very basic feature that needs to be added is the ability to copy an entire template with no inheritance/link to the original.  For example, you I have two different sections of my website, weddings and seniors.  I created a wedding template with the appropriate images and text widgets.  The intuitive thing would be to copy that entire template and then go through and change the text and swap out the images for senior-specific content.  Having to copy and paste and delete widgets to work around the inheritance issue is extremely cumbersome.  Being able to do whole blocks would help but copying the entire template with no inheritance is the most natural way to go about it.

**Comment by benjamintennant** [comment]
+1 Kevin Millard ticket 153689

**Comment by danjonlam** [comment]
+1 Michelle Lindsell ticket 155247

**Comment by benjamintennant** [comment]
+1 Brooke Whitney Photography ticket 155463

**Comment by benjamintennant** [comment]
+1 Nuria Bonser ticket 156289

**Comment by benjamintennant** [comment]
+1 Natalee ticket 157260

**Comment by danjonlam** [comment]
+1 Kevin Auyong ticket 157405

**Comment by danjonlam** [comment]
+1 Kate Mckenna ticket 157918

**Comment by postmastersteve** [comment]
+1 Jan Martin ticket 158016

**Comment by benjamintennant** [comment]
+1 Roy Somech ticket 158100

**Comment by benjamintennant** [comment]
+1 Louisa Ward ticket 158417 - wants to re-link inheritance and this would be a way to do it

**Comment by benjamintennant** [comment]
+1 Heather Espana ticket 158599

**Comment by benjamintennant** [comment]
+1 Kate Uhry ticket 158696 - wants to re-link inheritance and this would be a way to do it

**Comment by danjonlam** [comment]
+1 Jessssica ticket 158941

**Comment by danjonlam** [comment]
+1 Holly Sutor ticket 159499

**Comment by postmastersteve** [comment]
+1 Andrew Hind ticket 159962
deleted the footer block in a child template - wants to reestablish this from the base in his child template.

**Comment by benjamintennant** [comment]
+1 Aurore Létévé ticket 158949

**Comment by danjonlam** [comment]
+1 Jeremy Daly ticket 156432

**Comment by benjamintennant** [comment]
+1 Sascha Reinking ticket 160891

**Comment by danjonlam** [comment]
+1 Robert Radifera ticket 161028

**Comment by benjamintennant** [comment]
+1 Ilse Hetterscheid ticket 161053

**Comment by tonymayimages** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Lara Albuixech ticket 163105

**Comment by danjonlam** [comment]
+1 Sheena Gallegos ticket 163200

**Comment by jaredh159** [comment]
Completed in `6.19.0`.
