### ISSUE TITLE
Add ability to use dropdowns on vertical menu too

### ISSUE THREAD

**Issue by photog0411** [netrivet/prophoto-issues#483]
On horizontal menu, sub menu items appear as dropdown on hover. But on vertical menu they jus automatically show up under the main link. It looks very cluttered. Add ability for dropdown or slideover.

**Comment by jaredh159** [comment]
Thanks for your feedback!  I'm going to close this because we have a ticket open that covers this already:

https://github.com/netrivet/prophoto-issues/issues/282
