### ISSUE TITLE
Slow gallery animations prevent requests for more images

### ISSUE THREAD

**Issue by brianium** [netrivet/prophoto-issues#484]
Galleries with slow transition speeds prevent requests for more slides.

Galleries request more images from the server when a `slidechanged` event is received. If a user clicks to advance a gallery before an animation completes, the `slidechanged` event is never fired.

This would be a problem particularly with really slow crossfade timeouts.

**Comment by jaredh159** [comment]
+1 Megan Wynn 3620

**Comment by danjonlam** [comment]
+1 Kari Bellamy ticket 151470

**Comment by jaredh159** [comment]
Closing because fixed/added in [6.16.0](https://pro.photo/blog/prophoto-6-16-0) on 2/27/17.
