### ISSUE TITLE
Version transform checks fail on 32bit machines

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#485]
This causes errors uploading paid designs, because the transform steps are not executed.

By 1772, Leonhard Euler had proven that [2147483647](https://en.wikipedia.org/wiki/2147483647_(number)) was a prime number.

**Comment by lalunecreative** [comment]
Learn something new every day. lol

**Comment by creative-resort** [comment]
this number looks so nice in binary and other systems with base 2^x
