### ISSUE TITLE
Copy template not handling inheriting customizations correctly

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#492]
Steps to reproduce:

1. Migrate reset
2. Make a child template from Base
3. Edit child template and click row gear icon on the main content **row**
4. This customization will be in an _inheriting state_
5. Copy the child template
6. Edit _copied_ template and click row gear icon on the main content **row**

The same copied customization is **_not_** inheriting, from the base template, but it should be.  Our inheritance indicator is correct -- you can verify by changing the row-padding settings in the base template.  Changes will affect the original child template, but not the copied sibling.

**Comment by lalunecreative** [comment]
Except for Block titles on the copied sibling. Which still inherits. That has never made since to me.

**Comment by jaredh159** [comment]
Block titles don't technically _inherit_, they're just always shared by every template using the block.  But I see where you're coming from, @lalunecreative.

**Comment by lalunecreative** [comment]
To be honest to solve the whole thing would be to simply copy the layout over and not inherit at all. I think that's what we thought "copying" a template would be. That way we could edit the layout without having to delete anything or worry about inheriting anything back up to the top. I know inheriting is a big part of ProPhoto, but I don't think many or even any of us are using it design wise. Why would you want to edit a template only to have it change somewhere else you're not editing? The odds of anyone having multiples of the same page where they need such a thing is incredibly slim.

**Comment by lalunecreative** [comment]
Or another option would be to tell it exactly what you want to inherit so there's no mixup.

**Comment by jaredh159** [comment]
@lalunecreative thanks for the input, we're definitely considering all of your feedback regarding inheritance and hope to keep adding refinements to improve your workflow and give you what you need to build stuff fast and flexibly.
