### ISSUE TITLE
Improve tile transitions with hardware acceleration

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#501]
Using translate-3d which uses native hardware acceleration should prevent some of the fuzziness during transitions that can be seen currently.

Also look into removing css transition properties if the default and hover states are identical.

**Comment by lalunecreative** [comment]
+1 should speed up prophoto a bit, and get rid of the fuzziness I pointed out the other day. All for this one!

**Comment by jaredh159** [comment]
Fixed in https://github.com/netrivet/prophoto/pull/1038
