### ISSUE TITLE
Column inheritance issue when dragging widget from one row to another

### ISSUE THREAD

**Issue by brianium** [netrivet/prophoto-issues#507]
gasp! We have a template inheritance issue when dragging a widget from one row to another. It can result in terrifying templates like this:

![screen shot 2016-05-03 at 1 52 16 pm](https://cloud.githubusercontent.com/assets/636651/14992965/9af4a12c-1136-11e6-833d-000dc04a2012.png)

Basically, all columns are not having their inheritance broken as a result of this action.

**Comment by lalunecreative** [comment]
That sticky button is so weird...you guys couldn't put a little icon under the settings icon for the block? Wouldn't that make more since?  : )

**Comment by brianium** [comment]
@lalunecreative oops! I snapshotted this from a feature branch that is not quite finished. I assure you, we will do better than "Sticky?" lol

**Comment by lalunecreative** [comment]
Yeah I figured, just making sure! : )For a second I was like...uhh surely they wouldn't release it like that.

**Comment by brianium** [comment]
ProPhoto guys at work like:

![work](https://cloud.githubusercontent.com/assets/636651/14993414/aa2f563a-1138-11e6-8321-a8c0c5b99c31.gif)

**Comment by lalunecreative** [comment]
BAHAHAHA That's exactly how I always imagined it!

**Comment by brianium** [comment]
Steps to reproduce:

1. Create design from Campbell
2. Create child template from Base
3. Move featured button widget to "Slideshow Area" block
4. Go to Base template and resize featured button column (try increasing its size as far as you can go)
5. Go back to child template and get sad

**Comment by northfolkco** [comment]
thats so funny you'd say that, I was just talking to Sam like, "I wonder
how many times a day they say 'What the fuck'" LOL

On Tue, May 3, 2016 at 1:46 PM, Jared Henderson <notifications@github.com>
wrote:

> Closed #507 <https://github.com/netrivet/prophoto-issues/issues/507> via
> netrivet/prophoto#940 <https://github.com/netrivet/prophoto/pull/940>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/netrivet/prophoto-issues/issues/507#event-649331563>
>



-- 

Sam & Rachel  //  Design & Branding
Website <http://www.northfolk.co/>  //  Shop <http://shopnorthfolk.co>  //
Facebook <https://www.facebook.com/northfolkco>  //  ProPhoto
<http://www.prophoto.com/designer/northfolk>
