### ISSUE TITLE
Galleries are not displaying correctly

### ISSUE THREAD

**Issue by bdvphoto** [netrivet/prophoto-issues#508]
Latest update - galleries are no longer displaying correctly. When any gallery is opened the first image is displayed magnified and the slideshow does not start.

http://pasteboard.co/GdUOlWs.png

**Comment by bdvphoto** [comment]
This only started when I tried to hide play/pause controls on one of the galleries.

**Comment by jaredh159** [comment]
@bdvphoto yeah, we're going to look into this first thing this morning. we've had a couple people report the same thing

**Comment by jaredh159** [comment]
Fixed in beta56 auto-update.
