### ISSUE TITLE
Widget body H1 font-style overriding widget title font-style

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#511]
![2016-05-06_09-53-16](https://cloud.githubusercontent.com/assets/7050938/15075057/6f9cb582-1370-11e6-9267-7f4cbad40308.png)

The above settings cause widget titles to render _red_ instead of _green_.  We probably need to strengthen the css selector for widget titles, or, figure something else out. ¯\_(ツ)_/¯

**Comment by lalunecreative** [comment]
+1 for this one kinda annoying.
