### ISSUE TITLE
Gallery bound behavior jankiness in Safari

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#513]
See: https://prophoto.com/help/screenshots/2016-05-06_11-34-49.mp4

**Comment by postmastersteve** [comment]
+1 Yvette Johnson ticket 2610

**Comment by benjamintennant** [comment]
+1 Joly Stephane ticket 150210

In this video you see some images displaying in a gallery at full width but one displaying much smaller. It is not expanding. And... it's an intermittent problem. https://prophoto.com/help/screenshots/2016-11-09_16-45-21.mp4

**Comment by jaredh159** [comment]
Closing because fixed/added in [6.16.0](https://pro.photo/blog/prophoto-6-16-0) on 2/27/17.
