### ISSUE TITLE
Row columns responsive breakpoint padding not applied

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#514]
Or, as Rachel from @northfolkco put it: "Column padding is not working"

![2016-05-09_10-46-20](https://cloud.githubusercontent.com/assets/7050938/15116947/58fdae66-15d3-11e6-8b82-dc9a4160ceaa.png)

**Comment by brianium** [comment]
While we appreciate detail ... "Column padding is not working" is all kinds of correct. I'm on it!

**Comment by brianium** [comment]
@northfolkco fix incoming with the auto update today. Thanks for catching this! This bug was affecting a lot of responsive settings across the board so fixing it is pretty significant.
