### ISSUE TITLE
Sticky block intermittent problems

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#526]
Video: https://prophoto.com/help/screenshots/2016-05-13_10-44-25.mp4

Ticket: https://prophoto6.zendesk.com/agent/tickets/2314

**Comment by brianium** [comment]
Issue has to do with incorrectly calculating height for sticky blocks before a child image loads. This affects browsers that do not support native `position: sticky`. The solution is to calculate height once images have loaded in the block. Fix incoming!
