### ISSUE TITLE
Easier gallery management from post/page editor

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#527]
This includes:

1) the ability to click to edit a gallery already embedded in a post/page
2) the ability to create a new gallery from uploaded images without leaving the new/edit post/page screen

Also, possibly, a rich GUI for seeing all existing ProPhoto galleries and selecting them for insertion, or editing, etc.

**Comment by danjonlam** [comment]
+1 Amanda Howell ticket 145605

**Comment by benjamintennant** [comment]
+1 Paula Román ticket 147976 - wants to be able to insert a gallery as full sized images or to have the same ordering options available to images in a gallery, available with images in posts/pages

**Comment by benjamintennant** [comment]
+1 +1 Adam Nash ticket 148431 - wants to be able to insert a gallery as full sized images or to have the same ordering options available to images in a gallery, available with images in posts/pages

**Comment by danjonlam** [comment]
+1 Amber Starling ticket 151654

**Comment by postmastersteve** [comment]
+1 Carla Gates ticket 155433

**Comment by danjonlam** [comment]
+1 patrick ang ticket 155948

**Comment by benjamintennant** [comment]
+1 Simon Smith ticket 157447

**Comment by jaredh159** [comment]
Done in `6.17.0`.
