### ISSUE TITLE
Menu item reordering problems

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#533]
We've had a couple reports of customers having a really hard time re-ordering menu items, with menu items jumping around.  One ticket where it's easy to see the problem is:

https://prophoto6.zendesk.com/agent/tickets/2297

We need to take another pass at menu ordering, as it still seems too unreliable in the form it is in now.  It would be better probably to have an interface that required more clicks and actions and worked very reliably, if needs be.

**Comment by benjamintennant** [comment]
+1 Sven ticket 2407
