### ISSUE TITLE
Allow customizing & previewing of designs that aren't active

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#542]
A user should be able to have a P6 design designated as active, but be customizing another design "behind the scenes".

**Comment by jaredh159** [comment]
+1 Natasha 2566

**Comment by lalunecreative** [comment]
+1

**Comment by brianclaryphoto** [comment]
+1

**Comment by benjamintennant** [comment]
+1 kate ticket 3431

**Comment by danjonlam** [comment]
+1 Dalton Smiley ticket 147466

**Comment by danjonlam** [comment]
+1 Ariana Randle ticket 147536

**Comment by jaredh159** [comment]
Closed by `6.14.0`.
