### ISSUE TITLE
Dropping images to upload not working from ProPhoto galleries

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#548]
If you pop up the WordPress media modal by clicking "Add images" from a ProPhoto gallery edit screen, it looks like you can drop a file to upload (see below image) but the file does not actually upload.

![2016-06-01_09-10-45](https://cloud.githubusercontent.com/assets/7050938/15710624/db956564-27d8-11e6-953d-53a1e9b89658.png)

**Comment by jaredh159** [comment]
+1 Yvette 2520

**Comment by jaredh159** [comment]
+1 Ann 2412

**Comment by bdvphoto** [comment]
+1

**Comment by jaredh159** [comment]
Fixed in https://github.com/netrivet/prophoto/pull/1022
