### ISSUE TITLE
Customize submit button text for forms

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#550]
Currently the "submit" text for form submission buttons is hardcoded.  This is a challenge to our non-english users.  We should fairly quickly expose the option to modify that text, and also place a tile there instead.

**Comment by postmastersteve** [comment]
+1 Carlos Agnese ticket 2768

**Comment by benjamintennant** [comment]
+1 Corinne Kowal ticket 2967

**Comment by corinnekowal** [comment]
Tile would definitely be great!
Same as check boxes field

**Comment by postmastersteve** [comment]
+1 Kori Hiser ticket 143876
Submit button for **comment** forms

**Comment by benjamintennant** [comment]
+1 David Blair ticket 144073

**Comment by brianclaryphoto** [comment]
+1

**Comment by postmastersteve** [comment]
+1 Tanya Velazquez ticket 145988

**Comment by jaredh159** [comment]
Completed in `6.10.0`
