### ISSUE TITLE
Modify form submission email subject line

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#551]
Right now it's hard-coded to "New contact form submission".

**Comment by jaredh159** [comment]
+1 Juliana 141213

**Comment by brianclaryphoto** [comment]
+1

**Comment by postmastersteve** [comment]
+1 Alexander Fischer ticket 142623

**Comment by postmastersteve** [comment]
+1 Genia Chechersky ticket 142900

**Comment by postmastersteve** [comment]
+1 Warren Williams ticket 143371

**Comment by JenniferClare** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Joanie Fong ticket 3531

**Comment by danjonlam** [comment]
+1 Heiko Schmidt #3552

**Comment by danjonlam** [comment]
+1 Kali Poulsen ticket 144093

**Comment by jaredh159** [comment]
Completed in `6.7.0`
