### ISSUE TITLE
Use form submitted email address as "reply-to"

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#552]
Users like to be able to reply to their contact form submissions.  However, in P6 we don't require an email address as one of the form fields, so currently, we don't try to set a reply-to email address.  We should improve this.

Possibly, we could add a checkbox in the email field type form saying "use as reply-to"?  If that's not present we could do nothing, or check for a single email field?

**Comment by brianclaryphoto** [comment]
+1

**Comment by JenniferClare** [comment]
Yes please!

**Comment by danjonlam** [comment]
+1 Jennifer Cruger 141915

**Comment by danjonlam** [comment]
+1 Aimee Nelson 2917

**Comment by postmastersteve** [comment]
+1 Hailey Gonya ticket 142555

**Comment by danjonlam** [comment]
+1 Katherine Vess 142853

**Comment by postmastersteve** [comment]
+1 Katie Campbell ticket 142765

**Comment by northfolkco** [comment]
+1

**Comment by danjonlam** [comment]
+1 Kyle Parfait 143084

**Comment by postmastersteve** [comment]
+1 Randi Jasmine Davis ticket 142975

**Comment by danjonlam** [comment]
+1 Danielle Putonen 143312

**Comment by postmastersteve** [comment]
+1 Warren Williams ticket 143371

**Comment by danjonlam** [comment]
+1 Stephen Lamont 143485
