### ISSUE TITLE
Maintenance/coming soon mode

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#553]
P5 had it, a bunch of users have asked for it.  The right approach might be to actually not build this as a feature but instead do https://github.com/netrivet/prophoto-issues/issues/542 -- customizing and previewing of inactive designs.  If we did that, we could even bundle a super simple but slick looking "coming soon" _design_ that they could set as the active design for non-admin users while they worked on another one.

**Comment by jaredh159** [comment]
+1 Katrina 2688

**Comment by danjonlam** [comment]
+1 Celestina Ronquillo 141562

**Comment by brianclaryphoto** [comment]
+1

**Comment by danjonlam** [comment]
+1 Natasha 3009

**Comment by danjonlam** [comment]
+1 Shonta Harper 3082

**Comment by danjonlam** [comment]
+1 Jo O'Kelly 3316

**Comment by danjonlam** [comment]
+1 Steve Bennett 143338

**Comment by danjonlam** [comment]
+1 Brooke Dixon 3351

**Comment by danjonlam** [comment]
+1 Sarah Boni

**Comment by benjamintennant** [comment]
+1 Ben Karsay ticket 143858

**Comment by danjonlam** [comment]
+1 Andrew Hester 3607

**Comment by danjonlam** [comment]
+1 Taylor 3609

**Comment by danjonlam** [comment]
+1 Angela Ashcraft ticket 145222

**Comment by danjonlam** [comment]
+1 Abby Morris ticket 145257

**Comment by benjamintennant** [comment]
+1 Maryanne Souter ticket 145451

**Comment by benjamintennant** [comment]
+1 Kellie Biggs ticket 145551

**Comment by benjamintennant** [comment]
+1 Angela Lyons ticket 146276

**Comment by danjonlam** [comment]
+1 Morgan Cox ticket 146436

**Comment by benjamintennant** [comment]
+1 Joe Sinthavong ticket 146651

**Comment by danjonlam** [comment]
+1 Christian Montecillo ticket 146819

**Comment by danjonlam** [comment]
+1 Shellie Burkhalter ticket 148036

**Comment by danjonlam** [comment]
+1 Stacey Dennin ticket 147949

**Comment by danjonlam** [comment]
+1 Leela Bennett ticket 148192

**Comment by danjonlam** [comment]
+1 Jessica Strom ticket 148442

**Comment by danjonlam** [comment]
+1 Josh Schexnaildre ticket 148678

**Comment by danjonlam** [comment]
+1 Clare Steward ticket 148398

**Comment by jaredh159** [comment]
Closed by `6.14.0`.
