### ISSUE TITLE
FontStyle letter spacing needs to be em-based

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#562]
Currently letter-spacing doesn't scale with font size in tiles.

**Comment by postmastersteve** [comment]
+1 Megan Gonzalez ticket 143592

**Comment by danjonlam** [comment]
+1 Chris Smith 3943

**Comment by brianclaryphoto** [comment]
+1

**Comment by jaredh159** [comment]
Word-spacing needs to be addressed and fixed as well.

**Comment by postmastersteve** [comment]
+1 Amanda Basteen ticket 159016

**Comment by jaredh159** [comment]
Fixed in `6.16.0`
