### ISSUE TITLE
Support PHP7

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#563]

**Comment by postmastersteve** [comment]
+1 Joseph ticket 2777

**Comment by postmastersteve** [comment]
+1 Sven ticket 2548

**Comment by postmastersteve** [comment]
+1 Joseph Sarkodie ticket 2478

**Comment by postmastersteve** [comment]
+1 Violet Bowlan ticket 141680

**Comment by postmastersteve** [comment]
+1 Erika Rebstock ticket 141627

**Comment by lalunecreative** [comment]
+1

**Comment by brianium** [comment]
Went rogue and did this. Wasn't too bad and response times got like 100000000% better because PHP 7 is so future lol #swag

**Comment by brianium** [comment]
TBD if we are releasing this with a patch release or the next minor version (i.e 6.3)
