### ISSUE TITLE
Allow home and posts page Facebook og:image upload

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#566]
For the special pages of static front page and blog posts page, users should be able to upload a specified image for the Facebook `og:image` meta, like you could in P5.

**Comment by jaredh159** [comment]
+1 Andrea Kuntz 2808

**Comment by benjamintennant** [comment]
+1 Matt Hudson ticket 146752
>I've been seeing a TON of people talking about how they aren't getting the thumbnail when posting their site links to facebook... The photo upload has been stripped, and should probably be added back in, but I was sure that uploading a featured image to the home page should do the trick. I think this needs to be remedied sooner than later since I've been seeing so many complaints about it.

**Comment by postmastersteve** [comment]
+1 Emily Fiscus ticket 147512

**Comment by benjamintennant** [comment]
+1 beserilphotography ticket 148463

**Comment by benjamintennant** [comment]
+1 Stevie Cruz via Facebook support group

**Comment by benjamintennant** [comment]
+1 Heather Davis ticket 149429

**Comment by benjamintennant** [comment]
+1 Tahnee Williamson ticket 150890

**Comment by benjamintennant** [comment]
+1 James Powell ticket 151106

**Comment by postmastersteve** [comment]
+1 Jonica Weiler ticket 153721

**Comment by danjonlam** [comment]
+1 Sage Fitchett ticket 155111

**Comment by danjonlam** [comment]
+1 Chunmin Chen ticket 157094

**Comment by benjamintennant** [comment]
+1 Tiffany Rude ticket 158199

**Comment by jaredh159** [comment]
Closing because fixed/added in [6.16.0](https://pro.photo/blog/prophoto-6-16-0) on 2/27/17.
