### ISSUE TITLE
Trigger auto-update button & download latest build zip

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#570]
Users should be able to force trigger an auto-update, and/or download a `.zip` file of the latest build from within their admin settings area.

**Comment by lalunecreative** [comment]
Manual button. Auto updates don't work in our site thanks to a plugin we use, I have to force it with the url, so this would save me some time and effort.

**Comment by benjamintennant** [comment]
+1 RASHMI BHATT ticket 146656

**Comment by bdvphoto** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Amy Vecchio ticket 149745

**Comment by jaredh159** [comment]
Complete in `6.20.0`
