### ISSUE TITLE
Add setting for disabling read more link

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#575]
Not everyone wants to show this link.  Should provide this option in each context that it is an option.

**Comment by lalunecreative** [comment]
+1 All our designs got pushed with the update now have fugly looking buttons that were forced on when the feature was added. Could we make it that it's set off by default for grids at least?

**Comment by postmastersteve** [comment]
+1 Elon Reynolds ticket 3050

**Comment by danjonlam** [comment]
+1 Heiko Schmidt 3478

**Comment by danjonlam** [comment]
+1 Lindsey Medina 144011

**Comment by lalunecreative** [comment]
This one needs to be closed. Added in 6.7.0 not sure how it hasn't been realized yet.
