### ISSUE TITLE
Form radio/select (multiple-choice) fields

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#577]
Forms need a configurable field type for HTML radios and select (multiple choice)

**Comment by jaredh159** [comment]
+1 Sarah 141932

**Comment by northfolkco** [comment]
+1 NF

**Comment by lalunecreative** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Meredith Burke via feedback 142363

**Comment by benjamintennant** [comment]
+1 Stephanie Rimoux ticket 143449 wants dropdown multiple choice selection

**Comment by benjamintennant** [comment]
+1 Cassandra Nichols from feedback - wants dropdowns, checkboxes, conditional statements that open other form "pages"

**Comment by benjamintennant** [comment]
+1 Mihai Ruja ticket 3569 wants multiple choice dropdowns

**Comment by danjonlam** [comment]
+1 Chris 3698 wants dropdown options

**Comment by brianclaryphoto** [comment]
If possible, it would be fantastic if you could have both a display text and a backend text for each choice. This is helpful for passing values to other systems, where you want a 'user-friendly' display value in a dropdown but you need it to pass a more technical value on to another system.

**Comment by benjamintennant** [comment]
+1 Rachel Brown ticket 3740

**Comment by DoctibPhoto** [comment]
+1 radio, dropdowns, checkboxes

**Comment by jaredh159** [comment]
Closed by `6.9.0`
