### ISSUE TITLE
Potential resource limit reached on iOS devices when viewing large galleries

### ISSUE THREAD

**Issue by brianium** [netrivet/prophoto-issues#578]
Large galleries (in terms of total file size) may exhaust resources on iOS devices resulting in a crash.

A huge culprit here is uncompressed images - i.e A JPEG being 1.3 MB when it only needs to be 400 KB

The short answer here is to compress images better, but we may be able to improve how many gallery images are kept in memory at a given time

Sources:
1. http://www.fngtps.com/2010/mobile-safari-image-resource-limit-workaround/ - resource limits seem to have changed, but the issue and approach seem relevant still.
2. [Apple Developer Docs](https://developer.apple.com/library/mac/documentation/AppleApplications/Reference/SafariWebContent/CreatingContentforSafarioniPhone/CreatingContentforSafarioniPhone.html#//apple_ref/doc/uid/TP40006482-SW15)

**Comment by brianium** [comment]
Removing the `bug` label. We may be able to provide some useful behavior for this, but I would like to separate bugs from device/browser limitations. Adding a `device limitation` tag.

**Comment by danjonlam** [comment]
+5 - For the past customers I didn't add to this issue.

**Comment by postmastersteve** [comment]
+1 Kyle Hassall ticket 158305

**Comment by postmastersteve** [comment]
+1 Mary Tweedy ticket 159058

**Comment by postmastersteve** [comment]
+1 Rachel Walker ticket 155339

**Comment by postmastersteve** [comment]
+1 Fiona Murphy ticket 154421

**Comment by postmastersteve** [comment]
+1 Maureen Schwartz ticket 158952

**Comment by postmastersteve** [comment]
+1 Joanne Donaldson ticket 150906

**Comment by benjamintennant** [comment]
+1 Susan Tuttle ticket 158427
