### ISSUE TITLE
Customize form field widths

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#580]
In our initial implementation, form fields have some hard-coded max widths.  Users want to make these form fields full-width (100%) in some cases. But, in general, they should be able to control the width, sizing, spacing, etc, of the fields within a form.

**Comment by jaredh159** [comment]
+1 Corrine 2967

**Comment by lalunecreative** [comment]
+1 been coding this one.

**Comment by northfolkco** [comment]
+1

Ditto, we've been coding the whole thing to stylize it. I would be nice to get some stylization since P5 didn't have that.

**Comment by JenniferClare** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Benjamin Thorn 145483

**Comment by postmastersteve** [comment]
+1 Charles Diehle ticket 152211
would also like the ability to create columns of form fields

**Comment by benjamintennant** [comment]
+1 Lisa-Marie Chandler ticket 153134

**Comment by JenniferClare** [comment]
Would like to be able to centre the field text, have lines rather than boxes, as well as choose the width... pretty please

**Comment by postmastersteve** [comment]
+1 Claire Buys ticket 155951

**Comment by postmastersteve** [comment]
+1 Nikki van der Molen ticket 156377

**Comment by postmastersteve** [comment]
+1 Sajjad ticket 158109

**Comment by benjamintennant** [comment]
+1 Charlotte Razzell ticket 157231

**Comment by benjamintennant** [comment]
+1 Susan Tuttle ticket 158427

**Comment by postmastersteve** [comment]
+1 Chunmin Chen ticket 159946
width control (maybe with a `max-width` option?)

**Comment by jaredh159** [comment]
Completed in `6.18.0`.
