### ISSUE TITLE
Script or heavily slanted fonts getting cut off in tile text layers

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#582]

**Comment by lalunecreative** [comment]
Duplicate of this one, which is the oldest bug you guys currently have - https://github.com/netrivet/prophoto-issues/issues/127

**Comment by lalunecreative** [comment]
It's basically just for script fonts in general, everywhere in ProPhoto, it effects tiles, grids, and font styles. I've tested them in all 3.

**Comment by brianclaryphoto** [comment]
Glad I wasn't going crazy. I saw this but assumed it was something I had done :)

**Comment by brianium** [comment]
This issue just got fixed in the 6.3 branch - if we have other script font woes, we can move this conversation over to #127

**Comment by brianium** [comment]
Just to clarify, we fixed it specifically for tiles

**Comment by lalunecreative** [comment]
Aw why not fix it for the rest too? : )

**Comment by brianium** [comment]
That is definitely the plan :) - It's all these darn responsive nuances that make us break them up into separate issues.

**Comment by lalunecreative** [comment]
That makes since, I always wondered why only part of something got worked on instead of just finishing it out.

**Comment by jaredh159** [comment]
Released in 6.3.0.
