### ISSUE TITLE
Non-linking container menu items

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#589]
via @postmastersteve:

> There's no way to create a menu item that is nothing more than a container. Even with a custom link, it's got an <a> tag so you can click it.  Browsers refresh the page when this happens.
> 
> Proposing than menu items with no URL are stripped of their href completely so they don't behave as links. (preferred and more intuitive) **OR** Proposing that we create a menu item that acts strictly as a container, similar to P5.

**Comment by bdvphoto** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Nanda ticket 3403

**Comment by benjamintennant** [comment]
+1 Kimberly Wylie ticket 144622

**Comment by postmastersteve** [comment]
+1 Christian Sangree ticket 148044

**Comment by benjamintennant** [comment]
+1 Erika Roa ticket 153140

**Comment by benjamintennant** [comment]
+1 Penny Kendall ticket 153126

**Comment by benjamintennant** [comment]
+1 Kevin Millard ticket 153689

**Comment by benjamintennant** [comment]
+1 David Nguyen ticket 155179

**Comment by benjamintennant** [comment]
+1 Audrey Choate ticket 156146

**Comment by benjamintennant** [comment]
+1 Joanne Beecham ticket 156381

**Comment by bdvphoto** [comment]
+1 one as always have to use a tag at the moment for top menu items.

**Comment by benjamintennant** [comment]
+1 Ian Jeffery ticket 156409

**Comment by benjamintennant** [comment]
+1 Kim Kelley ticket 157654

**Comment by postmastersteve** [comment]
+1 Jakub Vozenilek ticket 159027

**Comment by benjamintennant** [comment]
+1 Pierre Violle ticket 162623

**Comment by benjamintennant** [comment]
+1 Tommi Kähärä ticket 162631

**Comment by benjamintennant** [comment]
+1 Christian Ingram ticket 162654

**Comment by benjamintennant** [comment]
+1 Kimberly Billings ticket 162981

**Comment by benjamintennant** [comment]
+1 Jennifer Dannatt ticket 163378

**Comment by jaredh159** [comment]
Completed in `6.19.0`.
