### ISSUE TITLE
Block reordering issues

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#590]
Because blocks can only be added at the **bottom** of a layout, a common scenario is to create a block there and then drag it up through many other blocks to get it to a higher position, or to the top.

But, if one is not careful to keep the mouse passing _through_ all the other blocks as you go up, blocks can get out of order, swapping places with each other in an unintuitive way.  This happens only when the mouse travels _outside_ of the main set of blocks, so as to skip mousing-over an intermediate block.  

You can see the problem in this short video clip.  I am trying to to move block three up to the top, so that the order would be 3, 1, 2, but instead 3 and 1 switch places, resulting in the order 3, 2, 1:

[![2016-06-19_15-24-04](https://cloud.githubusercontent.com/assets/7050938/16179382/e63a75ce-3631-11e6-88e8-e4bcd3b947a7.png)](https://www.prophoto.com/help/screenshots/2016-06-18_22-22-09.mp4)

It would be ideal if we could prevent this from happening.

**Comment by benjamintennant** [comment]
+1 Yvette Johnson ticket 3154 suggests easier ways to reorder blocks, like with numbers or arrows to click.
