### ISSUE TITLE
Allow setting "featured" images for categories

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#592]
These would be leveraged by "Categories" grids, similar to in P4/P5.  These images could be uploaded in the ProPhoto "Settings" area, or possibly in the WordPress category edit screen for each category.

Without this, it is difficult to exercise control over the appearance of a categories grid.  Especially if posts are often categorized with multiple categories, this can result in multiple categories finding and using the same image in a categories grid, which is not desired.

**Comment by benjamintennant** [comment]
+1 ticket 2656 Jessie
