### ISSUE TITLE
Image protection should prevent dragging onto the desktop

### ISSUE THREAD

**Issue by postmastersteve** [netrivet/prophoto-issues#594]
Currently, images can prevent left and right clicks, and they can have watermarks, but some users do not want watermarking. It's currently possible to simply drag any image to your desktop to save a high-res copy.

**Comment by postmastersteve** [comment]
+1 Daisy Beatty ticket 142451

**Comment by lalunecreative** [comment]
Yo steve, you need to apply labels to your tickets. : )

**Comment by lalunecreative** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Bryan Scott ticket 3335

**Comment by postmastersteve** [comment]
+1 Amy Haberland ticket 144241

**Comment by postmastersteve** [comment]
+1 Nathan Dang ticket 145094

**Comment by postmastersteve** [comment]
+1 Linda Morrow ticket 145296

**Comment by benjamintennant** [comment]
+1 Jackson Eddy ticket 145769

**Comment by postmastersteve** [comment]
+1 Birgit Hametner-Baldwin ticket 148885

**Comment by postmastersteve** [comment]
+1 Leslie Vega ticket 149326

**Comment by danjonlam** [comment]
+1 ketelsphotography@gmail.com ticket 151189 - Wants click/drag protection for gallery images

**Comment by benjamintennant** [comment]
+1 Steve Bennett ticket 151802

**Comment by postmastersteve** [comment]
+1 Guy ticket 152862

**Comment by benjamintennant** [comment]
+1 Sonja Rakicevic ticket 152698

**Comment by danjonlam** [comment]
+1 Lisa Coker ticket 154427

**Comment by benjamintennant** [comment]
+1 Roman Carvajal ticket 159684

**Comment by jaredh159** [comment]
Done in `6.17.0`.
