### ISSUE TITLE
Add post author options to post title header area

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#595]

**Comment by jaredh159** [comment]
+1 Brian Clary 3042

**Comment by lalunecreative** [comment]
+1

**Comment by postmastersteve** [comment]
+1 Joko Sanudin ticket 144148

**Comment by postmastersteve** [comment]
+1 Yvonne Blume ticket 148288
Wants post author options in post **footer area**

**Comment by benjamintennant** [comment]
+1 Marta Montilla from Facebook group

**Comment by benjamintennant** [comment]
+1 Rebecca Douglas ticket 150322 wants to show author to satisfy structure data markup

**Comment by postmastersteve** [comment]
+1 Kristina McCaleb ticket 150284

**Comment by rhondastarkdesign** [comment]
+1 client would like author

**Comment by benjamintennant** [comment]
+1 AnneMarie Simmons ticket 152437

**Comment by danjonlam** [comment]
+1 Kimberly Burleson ticket 152472

**Comment by danjonlam** [comment]
+1 Kristina McCaleb ticket 152770 - for structured data markup

**Comment by benjamintennant** [comment]
+1 Morgan Lang ticket 153739 - for structured data markup

**Comment by benjamintennant** [comment]
+1 Matt Selby ticket 156848 - for structured data makrup

**Comment by benjamintennant** [comment]
+1 Isabella Allamandri ticket 159401 - for structured data markup

**Comment by danjonlam** [comment]
+1 Kristine ticket 159417

**Comment by postmastersteve** [comment]
+1 Suzanne Taussig ticket 160237 - for structured data markup

**Comment by postmastersteve** [comment]
+1 Caroline Wilhite ticket 161247 - for structured data markup

**Comment by benjamintennant** [comment]
+1 marcus dinnage ticket 161625 - for structured data markup

**Comment by danjonlam** [comment]
+1 Claire Bear ticket 161585 - for structured data markup

**Comment by danjonlam** [comment]
+1 Helen Baldwin ticket 162947 - would like in the post footer area

**Comment by postmastersteve** [comment]
+1 Steve Bennett ticket 163404

**Comment by benjamintennant** [comment]
+1 Steven Davis ticket 163047 - for structured data markup

**Comment by benjamintennant** [comment]
+1 Christian Ingram ticket 163583

**Comment by benjamintennant** [comment]
+1 Ben ticket 165237 - interested in resolving structured data errors

**Comment by benjamintennant** [comment]
+1 ProPhoto Help Site Feedback ticket 165686

**Comment by benjamintennant** [comment]
+1 Oksana Kuklina ticket 165835 - for structured data

**Comment by benjamintennant** [comment]
+1 Ricardo Freitas ticket 167589 - to solve structured data errors.

**Comment by benjamintennant** [comment]
+1 Aysegul Sanford ticket 167774 - so solve structured data errors

**Comment by benjamintennant** [comment]
+1 Travis Borkenhagen ticket 167498 - to solve structured data errors

**Comment by benjamintennant** [comment]
+1 Oliver Juric ticket 169001 - has multiple authors and wants to display names in post header

**Comment by benjamintennant** [comment]
+1 Satnam Singh ticket 169104 - to solve structured data errors

**Comment by benjamintennant** [comment]
+1 Lisa Whitmore ticket 169834 - to solve structured data errors

**Comment by postmastersteve** [comment]
Fixed in ProPhoto 6.21.0
https://github.com/netrivet/prophoto-issues/blob/master/CHANGELOG.md#6210
