### ISSUE TITLE
Form submit success url redirects

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#599]
Forms should allow a url to be specified for redirection after a successful submission. This would allow for a lot things, including templated dynamic success pages using submitted info data, google analytics tracking and goal/conversion tracking, etc.

**Comment by lalunecreative** [comment]
+1 It would be pretty nice to design a template "success page" for the contact form.

**Comment by postmastersteve** [comment]
+1 Jessica Rotenberg ticket 142726

**Comment by JenniferClare** [comment]
+1

**Comment by benjamintennant** [comment]
+1 Sarah Jones - wants a success page to add Facebook tracking pixel to.

**Comment by postmastersteve** [comment]
@jaredh159 
I was searching for a different Form issue to log something and discovered this.
We solved this in 6.7.0 but this Issue was left open. FYI

**Comment by jaredh159** [comment]
Added in `6.7.0`
