### ISSUE TITLE
P5 settings not imported

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#619]
Right now, P6 does not attempt any import of "settings" from P5/P4 (what was considered "global options" in those versions).

This is problematic because some of these are very significant in the initial user experience, and feel like bugs:

1. `pathfixer_old_urls` is not imported, leading to broken images on old posts
2. footer link removal data is also not imported, causing additional work to get links hidden again

Also, we should whitelist certain other legacy settings (including a bunch of "translation" settings) to smooth the experience for upgraders, since the conversion is extremely straightforward.

**Comment by postmastersteve** [comment]
+1 Jeff Ascough ticket 143383

**Comment by jaredh159** [comment]
Also, Google Analytics code would be nice.

**Comment by postmastersteve** [comment]
+1 Natalia Demidova ticket 143870
