### ISSUE TITLE
Update to Version 6.4.6 Messes up Template Assignements

### ISSUE THREAD

**Issue by bdvphoto** [netrivet/prophoto-issues#621]
Just auto updated to v 6.4.6  and now every page is using my home page template and ignoring the template assignments.  When try to get into template assignments in ProPhoto Customizer just hangs.

**Comment by jaredh159** [comment]
Looking into this right no @bdvphoto, thanks for the report.  If you want to revert to 6.4.5, just log in to your WordPress admin area and go to "Settings" > "Options".  After the page is loaded, add:

`?pp_force_updates=1&ignore_delay=1`

to the URL in your browser, and press enter to load the page again with the addition.  This will force P6 to revert to `6.4.5`.  So if your website is:

`http://www.mysite.com/`

Then, the url you would hit to revert is:

`http://www.mysite.com/wp-admin/options.php?pp_force_updates=1&ignore_delay=1`
