### ISSUE TITLE
some tiles load in editor with decimal height value

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#649]
![screen shot 2016-07-27 at 10 19 41 am](https://cloud.githubusercontent.com/assets/11544705/17178715/8b191594-53e4-11e6-855b-419833b935db.png)
This is actually correct, because technically tile height is always calculated as a percentage of the width for responsive rendering.  However, creating a tile with a width of say 225, and then having it display 225.0003 is confusing, so this should always be rounded to a whole number when displaying it in the editor.

**Comment by lalunecreative** [comment]
Well that and it makes borders cut off on tiles on one side if you have borders set. I want to make that clear in case that particular issue doesn't get fixed.

**Comment by bdvphoto** [comment]
+1 just for the borders not displaying on one side
