### ISSUE TITLE
Show that required form fields are required before validation

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#657]
An `*` or `- (required)` or something like that, some sort of user-customizable way of indicating which fields are required.  Right now there is just error validation on submit.

**Comment by jaredh159** [comment]
+1 Cheryl ticket 3761

**Comment by postmastersteve** [comment]
+1 Chunmin Chen ticket 159946
wants an * asterisk to indicate required fields

**Comment by lalunecreative** [comment]
+1 to cut down user confusion, accessibility, and overall good design feels.

**Comment by lalunecreative** [comment]
This one got done in 6.19.  Thanks @meatwad5675
