### ISSUE TITLE
Vertical alignment options for rollover grid text

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#676]
Particularly the ability to vertically center the text like so:

![2016-08-24_21-58-27](https://cloud.githubusercontent.com/assets/7050938/17954005/00defad8-6a46-11e6-91a5-4a2d6687d27c.png)

But probably should include top, center, and bottom.

**Comment by jaredh159** [comment]
via @lalunecreative:

> Vertical alignment of grid item text needs to be added.

**Comment by jaredh159** [comment]
+1 for vertical alignment of rollover text from David in #1789

**Comment by jaredh159** [comment]
+1 Courtney Keim - vertical centering of text on rollover style

**Comment by jaredh159** [comment]
+1 Kati #2519 - for vertical text alignment options (top, center, bottom)

**Comment by benjamintennant** [comment]
+1 Ashley Jankowski ticket 146318

**Comment by northfolkco** [comment]
++++
