### ISSUE TITLE
Font style preview background broken

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#696]
Since `6.10.0` when we introduced opacity to all color pickers, we seem to have lost the font style preview background turning black when necessary:

![2016-09-07_13-59-22](https://cloud.githubusercontent.com/assets/7050938/18322977/68177f0a-7503-11e6-910c-c154c828fa7d.png)

**Comment by benjamintennant** [comment]
+1 Henley Bailey ticket 146864

**Comment by jaredh159** [comment]
Fixed by https://github.com/netrivet/prophoto/pull/1210 -- will go out in `6.11.2`.
