### ISSUE TITLE
Fatal error in very old builds of PHP 5.3

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#702]
Looks like `6.11.0` introduced an error that affects only very rare, early versions of PHP 5.3:

![2016-09-14_17-41-47](https://cloud.githubusercontent.com/assets/7050938/18531136/bc265ee6-7aa2-11e6-8122-e90932c77f2b.png)

**Comment by jaredh159** [comment]
https://prophotoblogs.zendesk.com/agent/tickets/146952

**Comment by brianium** [comment]
I don't think we are going to address this. We are pushing people more towards newer PHP versions (which is an option most hosts support these days).

This is also complicated by the fact that it is a very old version of PHP 5.3 (so not even a stable version of a PHP version that has been end of lifed).
