### ISSUE TITLE
Some users having problems auto-updating since WordPress 4.6

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#704]
WordPress 4.6 stopped making use of the `http_api_curl` action, which we were using to fix problems on a small percentage of our users with out-of-date SSL server software.  There's a ticket open on the WordPress public tracker:

https://core.trac.wordpress.org/ticket/37843

For affected users (we're guessing 5% or less), this change in WordPress `4.6` is causing their ProPhoto auto-updates to fail.

Our original ticket here: https://github.com/netrivet/prophoto-issues/issues/445

This is not a bug we can fix currently, we're waiting for WordPress to fig the regression and give us access to modify the `curl` request like we used to have.  If this bug is affecting you, and you want to +1 the WordPress trac ticket (first link above), that might help make sure they know this is causing problems.  If you mention a desire that the fix would be in the `4.6.x` branch instead of the `4.7` branch, the fix _might_ come sooner.

**Comment by jaredh159** [comment]
https://prophotoblogs.zendesk.com/agent/tickets/147060 to test the fix when WordPress releases a change.

**Comment by lalunecreative** [comment]
I +1 the ticket for you guys. Wordpress.org's registration form is nowhere to be seen I had to dig for that thing just to comment.

**Comment by jaredh159** [comment]
The WordPress ticket has been escalated and scheduled for a fix to land in `4.6.2`, which is good news, it should be here sooner than waiting for `4.7.0`.

**Comment by jaredh159** [comment]
Fix landed in `4.7.0`
