### ISSUE TITLE
Customizer in multiple tabs can cause issues

### ISSUE THREAD

**Issue by brianium** [netrivet/prophoto-issues#711]
If work in the customizer begins in one tab, and then the customizer is opened in another tab - it is currently possible to make changes in both tabs.

The downside of this is that both tabs could have different states, which would allow a user to potentially overwrite changes from one tab in another.

We currently lock down the customizer from other users (different browsers, different computers), but to prevent this tab issue we need to lock down the customizer for a single session - that is prevent multiple tabs as well as multiple browsers/computers

**Comment by brianclaryphoto** [comment]
+1
