### ISSUE TITLE
Allow inserting of gallery into post as full-sized images

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#715]
Similar to what we allowed in P4/P5.  Many people seem to be using the workflow of creating a gallery, and then wanting to dump all gallery images into the post.

**Comment by jaredh159** [comment]
+1 Rayan Anastor ticket 147582

**Comment by jaredh159** [comment]
+1 Thiebauld Ben Lahoussine ticket 146750

**Comment by jaredh159** [comment]
+1 Gary Chen ticket 146215

**Comment by brianclaryphoto** [comment]
+1

**Comment by lalunecreative** [comment]
+1

**Comment by danjonlam** [comment]
+1 Manuela Angelli ticket 149494

**Comment by danjonlam** [comment]
+1 Amanda Schwinghammer ticket 149623 - to be able to easily reorder images before inserting

**Comment by danjonlam** [comment]
+1 Marina Bushneva ticket 150892

**Comment by danjonlam** [comment]
+1 Ross Hurley ticket 151292

**Comment by danjonlam** [comment]
+1 Jess Burges ticket 149660

**Comment by postmastersteve** [comment]
+1 Nicholas Pitt ticket 151852

**Comment by danjonlam** [comment]
+1 Redijus Anikanovas ticket 151824

**Comment by benjamintennant** [comment]
+1 Jeff Ascough ticket 152132

**Comment by benjamintennant** [comment]
+1 Ana Parker Photography ticket 152549

**Comment by benjamintennant** [comment]
+1 Denise Blommestyn ticket 152637

**Comment by danjonlam** [comment]
+1 Jayson Quinn ticket 152773

**Comment by danjonlam** [comment]
+1 Gabriela Burton ticket 153829

**Comment by danjonlam** [comment]
+1 Claude Masselot ticket 153959

**Comment by danjonlam** [comment]
+1 Paul Tansley ticket 157180

**Comment by bdvphoto** [comment]
Everything has come to a standstill..are you guys still developing this?

**Comment by jaredh159** [comment]
@bdvphoto we've put out several recent updates. You can always check our changelog for the most recent changes:

https://github.com/netrivet/prophoto-issues/blob/master/CHANGELOG.md

Our focus for the last little bit has been on rebuilding our site, as mentioned on our blog:

https://pro.photo/blog/our-new-p6-site

But we've shifted back to even more development of P6, which never fully stopped even while we were rebuilding our main site and infrastructure.

**Comment by danjonlam** [comment]
+1 Chris ticket 158048

**Comment by danjonlam** [comment]
+1 Janelle Rose ticket 158350

**Comment by jaredh159** [comment]
Closing because fixed/added in [6.16.0](https://pro.photo/blog/prophoto-6-16-0) on 2/27/17.
