### ISSUE TITLE
WooCommerce Support

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#723]

**Comment by jaredh159** [comment]
+1 Todd & Tisa ticket 149862

**Comment by jaredh159** [comment]
+1 Leonardo Pereira Vivas ticket 149528

**Comment by jaredh159** [comment]
+1 Melody Bennett ticket 149259

**Comment by jaredh159** [comment]
+1 Sarah Poplimont ticket 146917

**Comment by jaredh159** [comment]
+1 Haseeb Dev ticket 148977

**Comment by benjamintennant** [comment]
+1 Todd & Tisa ticket 149862

**Comment by benjamintennant** [comment]
+1 Darren Modricker ticket 150282

**Comment by danjonlam** [comment]
+1 Elisa Hardy ticket 150184

**Comment by benjamintennant** [comment]
+1 Margaux Bellanger ticket 150514

**Comment by benjamintennant** [comment]
+1 Shantal Hetlinger ticket 150565

**Comment by benjamintennant** [comment]
+1 Kendra Swalls ticket 150601

**Comment by postmastersteve** [comment]
+1 Loreta Labarca ticket 151277

**Comment by danjonlam** [comment]
+1 Malte Clavin ticket 151172

**Comment by benjamintennant** [comment]
+1 Jennifer Hejna ticket 151435

**Comment by postmastersteve** [comment]
+1 Peter Sequeira ticket 151696

**Comment by benjamintennant** [comment]
+1 Sandra Hegedus ticket 151613

**Comment by danjonlam** [comment]
+1 Antony Booker ticket 151892

**Comment by benjamintennant** [comment]
+1 Wisam Mahmood ticket 152420

**Comment by postmastersteve** [comment]
+1 Tanja Walter ticket 152888

**Comment by benjamintennant** [comment]
+1 Kate ticket 153454

**Comment by postmastersteve** [comment]
+1 Catherine Adelbert ticket 153732

**Comment by danjonlam** [comment]
+1 Viktor Isaak ticket 154275

**Comment by danjonlam** [comment]
+1 Chloe Hilton ticket 154964

**Comment by benjamintennant** [comment]
+1 David Miller ticket 155101

**Comment by danjonlam** [comment]
+1 Jan Oscarsson ticket 156423

**Comment by benjamintennant** [comment]
+1 Sandra Manas ticket 156972

**Comment by benjamintennant** [comment]
+1 Tony Kim ticket 157455

**Comment by benjamintennant** [comment]
+1 Elisa Hardy ticket 157516

**Comment by jaredh159** [comment]
Closing because fixed/added in [6.16.0](https://pro.photo/blog/prophoto-6-16-0) on 2/27/17.
