### ISSUE TITLE
Disable OG meta for plugin compatibility

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#724]

**Comment by jaredh159** [comment]
+1 Greg Benz ticket 149703

**Comment by jaredh159** [comment]
+1 Scott McIntyre ticket 149059

**Comment by jaredh159** [comment]
+1 Greg Benz ticket 148942

**Comment by benjamintennant** [comment]
+1 James Powell ticket 151106

**Comment by benjamintennant** [comment]
+1 Alicia Scott ticket 152663

**Comment by benjamintennant** [comment]
+1 Joelle Leger ticket 153566

**Comment by postmastersteve** [comment]
+1 Matt Selby ticket 154459

**Comment by benjamintennant** [comment]
+1 Eric Schwanke ticket 157828

**Comment by benjamintennant** [comment]
+1 Tiffany Rude ticket 158199

**Comment by jaredh159** [comment]
Closing because fixed/added in [6.16.0](https://pro.photo/blog/prophoto-6-16-0) on 2/27/17.
