### ISSUE TITLE
Allow setting img alt attribute for graphics widget images

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#725]
For theoretical SEO benefits, I suppose.

**Comment by jaredh159** [comment]
+1 Steve Chaplin ticket 148702

**Comment by jaredh159** [comment]
+1 Michael Gronow ticket 148514

**Comment by benjamintennant** [comment]
+1 Heiko Schmidt ticket 151286

**Comment by benjamintennant** [comment]
+1 Janine Guidera ticket 154937

**Comment by danjonlam** [comment]
+1 David Wallters ticket 155377

**Comment by postmastersteve** [comment]
+1 Dawn Martin ticket 155692

**Comment by postmastersteve** [comment]
+1 Melissa Pfannenstiel ticket 155783

**Comment by fuelyourphotos** [comment]
I agree that this isn't at the TOP of the priority list for SEO with typical usage of the graphics widget, but I do think it depends on how the owner of the site is using these widgets. Having the ability to add alt text can be more or less critical depending on a number of other factors. 

So while I can see why you say "theoretical" I do think this is absolutely best practice, not only for SEO but also for usability and accessibility.

**Comment by danjonlam** [comment]
+1 Paul Tansley ticket 156413

**Comment by shnurov** [comment]
+1 for me!

**Comment by benjamintennant** [comment]
+1 Audrey Choate ticket 157665

**Comment by danjonlam** [comment]
+1 Sarah Henry ticket 158441

**Comment by lalunecreative** [comment]
+1

**Comment by jaredh159** [comment]
Done in `6.17.0`.
