### ISSUE TITLE
Pinit overlay problems with small or left/right aligned images

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#726]
1. pinit overlay is getting `width: 100%` which doesn't make sense for images smaller than the parent container.
2. images set to be aligned right or left are not displaying correctly because of the 100% width
3. `<div>` tags are being rendered _inside_ `<p>` tags, which is invalid, and causes Chrome to do weird things

![2016-11-07_10-10-00](https://cloud.githubusercontent.com/assets/7050938/20062730/c1a0e148-a4d2-11e6-8f03-a88595d3b617.png)

**Comment by postmastersteve** [comment]
+1 Carlos Espinoza ticket 149988
When a photo exists in the content, but the image isn't large enough to grow to 100% width, the Pinterest overlay expands to 100% independent of the image width.

**Comment by danjonlam** [comment]
+1 PJ Geonzon - https://prophotoblogs.zendesk.com/agent/tickets/150009
