### ISSUE TITLE
Customizer is unusable

### ISSUE THREAD

**Issue by bdvphoto** [netrivet/prophoto-issues#729]
The ProPhoto customizer has become unusable - 90% of the time just get the :+1: 

Oops! An error has occurred
An unknown error has occurred
Sorry, an error occurred. We recommend that you refresh the page and try again. If the problem persists, please contact us for more help.

Impossible to do anything with it.

Oh..and we cannot contact you directly as your site is down.

**Comment by jaredh159** [comment]
@bdvphoto really sorry. Bluehost (who we host with currently) is having some major problem. It sounds like they are getting closer to a resolution. 

Once that is resolved, send us a support ticket through our site with your wp and ftp login and we'll take a look. Try disabling plugins first as we know of at least one buggy plugin that can cause the exact problem you're describing.
