### ISSUE TITLE
widget body blockquotes :: selector not sufficiently specific

### ISSUE THREAD

**Issue by creative-resort** [netrivet/prophoto-issues#743]
Blockquote styles e.g. a font setting in
**column settings > Font Area > body blockquotes**
aren't applied properly

because the used CSS selector addresses only the blockquote element.

By standard in the P6 Text Widget, at least a paragraph element is used from start,
which when a blockquote is applied, is wrapped in the blockquote element resulting in
```
<blockquote>
  <p>TEXT</p>
</blockquote>
```

The existing CSS style for
`.pp-widget div,.pp-widget p`

overwrites the blockquote styling.

The selectors should also address
`blockquote p`

**Comment by brianium** [comment]
@creative-resort thanks for opening this - I'm going to label it as a bug so we can smash it

**Comment by brianium** [comment]
@creative-resort a fix for this has been merged - the next auto update should include the fix. Thanks for your patience on this!
