### ISSUE TITLE
Viewport visibility movement

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#746]
Add the ability to specify transition effects that get applied to elements as they become visible due to scrolling.

Example: as a user scrolls down a ProPhoto page to where they can see a block containing some image and text widgets, add a subtle fade in or position animation to snap the item into place and focus as it comes into the viewport.

**Comment by TimKamppinen** [comment]
It would be great if this can be applied to elements within a block as well instead of the just the entire block. For instance a block with a background image and a text widget centered over it, where the background image is visible the whole time but the text fades in only as you scroll down.

**Comment by benjamintennant** [comment]
+1 Ryan Beuke ticket 160901

**Comment by jaredh159** [comment]
Completed in `6.19.0`.
