### ISSUE TITLE
Do not add a fallback menu when no menu widget exists

### ISSUE THREAD

**Issue by postmastersteve** [netrivet/prophoto-issues#775]
It is unnecessarily confusing to ask users to hide a menu widget at all breakpoint widths just to achieve a page where they might not want a desktop nav menu. For example, when they choose to use the mobile menu at all screen sizes.

Do not add the menu automatically to the layout when no menu widget exists in the layout.

**Comment by postmastersteve** [comment]
+1 Tracy Wicklund ticket 168379

**Comment by benjamintennant** [comment]
+1 Sarah Henry ticket 170293

**Comment by postmastersteve** [comment]
Fixed in ProPhoto 6.21.0
https://github.com/netrivet/prophoto-issues/blob/master/CHANGELOG.md#6210
