### ISSUE TITLE
Option to remove ProPhoto generated structured data

### ISSUE THREAD

**Issue by benjamintennant** [netrivet/prophoto-issues#796]
More and more people want to add custom structured data to their sites. There are many plugins for this but even when they correctly implement it, our structured data injections are generating errors. An option to remove our structured data allows for a plugins to completely handle this.

**Comment by benjamintennant** [comment]
+1 Daren Ng ticket 146158

**Comment by postmastersteve** [comment]
Our structured data implementation was removed in ProPhoto 6.21.0
https://github.com/netrivet/prophoto-issues/blob/master/CHANGELOG.md#6210
