### ISSUE TITLE
Update structured data implementation to JSON/LD method

### ISSUE THREAD

**Issue by benjamintennant** [netrivet/prophoto-issues#797]
We are currently using an older method of structured markup implementation. There are some outdated methods being used resulting in hentry errors. These need to be updated and it seems like the right way to do that is also switch to the recommended implementation method using javascript.

**Comment by postmastersteve** [comment]
Our structured data implementation was removed in ProPhoto 6.21.0
https://github.com/netrivet/prophoto-issues/blob/master/CHANGELOG.md#6210
