### ISSUE TITLE
Option to change or remove pp_gallery from gallery permalinks

### ISSUE THREAD

**Issue by benjamintennant** [netrivet/prophoto-issues#798]
Currently, our gallery custom post type permalinks all have /pp_gallery/ before the slug. An option to remove that or change it would be a welcome addition.

**Comment by benjamintennant** [comment]
+1 Chelsea Paulus ticket 170067

**Comment by postmastersteve** [comment]
This was completed in ProPhoto 6.21.0
https://github.com/netrivet/prophoto-issues/blob/master/CHANGELOG.md#6210
