### ISSUE TITLE
File upload areas with no image showing options

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#86]
![useless-options](https://cloud.githubusercontent.com/assets/7050938/11860387/4ced247e-a442-11e5-8764-0d52eb36f76b.jpg)

**Comment by northfolkco** [comment]
I've talked with Matt about this. Seems to be a host cache override.

To correct this I needed to go to Hosting > Performance > Cache Control and
turn all off. I created a new subdominant today and it happened again and I
had to go back in and turn it off.

On Wednesday, December 16, 2015, Jared Henderson <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> [image: useless-options]
> <https://cloud.githubusercontent.com/assets/7050938/11860387/4ced247e-a442-11e5-8764-0d52eb36f76b.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netrivet/prophoto-issues/issues/86>.
>


-- 

Sam & Rachel  //  Design & Branding
Website <http://www.northfolk.co/>  //  Facebook
<https://www.facebook.com/northfolkco>  //  ProPhoto
<http://www.prophoto.com/designer/northfolk>
